# -*- coding: utf-8 -*-
"""QAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwsoRkog6S04XfzxswS74Hw1Xx_bIDqS
"""

!pip install lpips
!pip install torchmetrics

import kagglehub

# Download latest version
path = kagglehub.dataset_download("xhlulu/140k-real-and-fake-faces")

print("Path to dataset files:", path)


from google.colab import drive
import os

print("Đang kết nối Google Drive...")
drive.mount('/content/drive')

import os
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
from PIL import Image
#import lpips
import numpy as np
import matplotlib.pyplot as plt

# ==============================================================================
# 0. CẤU HÌNH (CONFIG)
# ==============================================================================
class Config:
    # Đường dẫn dữ liệu
    TRAIN_REAL_DIR = "/kaggle/input/140k-real-and-fake-faces/real_vs_fake/real-vs-fake/train/real"
    VAL_REAL_DIR = "/kaggle/input/140k-real-and-fake-faces/real_vs_fake/real-vs-fake/valid/real"

    # Đường dẫn lưu model
    DRIVE_PATH = "/content/drive/MyDrive/final/final1"
    SAVE_DIR = os.path.join(DRIVE_PATH, "qat_results_q6_10")

    # Tham số huấn luyện QAT (Fine-tuning)
    IMG_SIZE = 128
    BATCH_SIZE = 32
    NUM_EPOCHS = 10       # Chỉ cần train ngắn (5-10 epoch) để thích nghi
    LEARNING_RATE = 1e-5  # LR rất nhỏ để tinh chỉnh
    LEARNING_RATE_DISC = 1e-5
    BASE_CHANNEL = 32

    # Trọng số Loss
    LAMBDA_ADV = 0.05
    LAMBDA_SECRET = 5.0
    LAMBDA_COVER_L1 = 1.0
    LAMBDA_COVER_L2 = 1.0
    LAMBDA_COVER_LPIPS = 1.0

    # Thiết bị
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

os.makedirs(Config.SAVE_DIR, exist_ok=True)
print(f"Cấu hình QAT đã sẵn sàng. Thiết bị: {Config.DEVICE}")

# ==============================================================================
# 1. CORE QUANTIZATION (Q6.10)
# ==============================================================================
class FakeQuantizeQ6_10(torch.autograd.Function):
    """
    Q6.10 Format:
    - Scale: 1024 (2^10)
    - Range: [-32768, 32767] (Tương ứng [-32.0, 31.999] trong thực tế)
    """
    @staticmethod
    def forward(ctx, x):
        scale = 1024.0
        # Nhân scale -> Làm tròn -> Kẹp giới hạn 16-bit -> Chia scale
        return torch.round(x * scale).clamp(-32768, 32767) / scale

    @staticmethod
    def backward(ctx, grad_output):
        # STE: Cho gradient đi qua nguyên vẹn
        return grad_output

def qat_quant(x):
    return FakeQuantizeQ6_10.apply(x)

class QuantIdentity(nn.Module):
    """Layer dùng để chèn qat_quant vào nn.Sequential"""
    def forward(self, x):
        return qat_quant(x)

# ==============================================================================
# 2. QAT BLOCKS (WEIGHTS & ACTIVATIONS)
# ==============================================================================

class QATSeparableConv2d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1):
        super().__init__()
        # Giữ nguyên tên biến để load được weights cũ
        self.depthwise = nn.Conv2d(in_channels, in_channels, kernel_size, stride, padding, groups=in_channels, bias=False)
        self.pointwise = nn.Conv2d(in_channels, out_channels, kernel_size=1, bias=False)

    def forward(self, x):
        # 1. Quantize Weights trước khi Conv
        w_dw = qat_quant(self.depthwise.weight)
        w_pw = qat_quant(self.pointwise.weight)

        # 2. Depthwise Conv
        x = F.conv2d(x, w_dw, self.depthwise.bias, self.depthwise.stride,
                     self.depthwise.padding, self.depthwise.dilation, self.depthwise.groups)

        # (Option) Quantize output trung gian (Depthwise Out)
        x = qat_quant(x)

        # 3. Pointwise Conv
        x = F.conv2d(x, w_pw, self.pointwise.bias, self.pointwise.stride,
                     self.pointwise.padding, self.pointwise.dilation, self.pointwise.groups)
        return x

class QATEncoder(nn.Module):
    def __init__(self, base_c=32):
        super().__init__()

        def qat_conv_block(in_c, out_c, stride=1):
            return nn.Sequential(
                QATSeparableConv2d(in_c, out_c, stride=stride),
                nn.BatchNorm2d(out_c),
                nn.ReLU(True),
                QuantIdentity() # Quantize Activations sau ReLU
            )

        self.head = qat_conv_block(6, base_c)
        self.down1 = qat_conv_block(base_c, base_c*2, stride=2)
        self.down2 = qat_conv_block(base_c*2, base_c*4, stride=2)
        self.bottleneck = qat_conv_block(base_c*4, base_c*8, stride=2)

        self.upsample = nn.Upsample(scale_factor=2, mode='nearest')
        self.up1 = qat_conv_block(base_c*8 + base_c*4, base_c*4)
        self.up2 = qat_conv_block(base_c*4 + base_c*2, base_c*2)
        self.up3 = qat_conv_block(base_c*2 + base_c, base_c)

        # Layer cuối dùng Conv thường (Pointwise)
        self.tail_conv = nn.Conv2d(base_c, 3, kernel_size=1, bias=False)
        self.tanh = nn.Tanh()

    def forward(self, x_cover, x_secret):
        # QUAN TRỌNG: Quantize Input (giả lập ảnh 16-bit vào FPGA)
        x_cover = qat_quant(x_cover)
        x_secret = qat_quant(x_secret)

        x = torch.cat([x_cover, x_secret], dim=1)
        c1 = self.head(x)
        c2 = self.down1(c1)
        c3 = self.down2(c2)
        b  = self.bottleneck(c3)

        u1 = self.up1(torch.cat([self.upsample(b), c3], dim=1))
        u2 = self.up2(torch.cat([self.upsample(u1), c2], dim=1))
        u3 = self.up3(torch.cat([self.upsample(u2), c1], dim=1))

        # Quantize weight lớp cuối
        w_tail = qat_quant(self.tail_conv.weight)
        out = F.conv2d(u3, w_tail, stride=1)

        # Quantize Output của mạng (trước khi cộng residual)
        out = qat_quant(self.tanh(out))

        return torch.clamp(x_cover + out, -1, 1)

class QATDecoder(nn.Module):
    def __init__(self, base_c=32):
        super().__init__()

        def qat_conv_block(in_c, out_c, stride=1, kernel=3, padding=1):
             return nn.Sequential(
                      QATSeparableConv2d(in_c, out_c, kernel_size=kernel, stride=stride, padding=padding),
                      nn.BatchNorm2d(out_c),
                      nn.ReLU(True),
                      QuantIdentity() # Quantize Activations
            )

        self.head = qat_conv_block(3, base_c)
        self.down1 = qat_conv_block(base_c, base_c*2, stride=2)
        self.down2 = qat_conv_block(base_c*2, base_c*4, stride=2)
        self.down3 = qat_conv_block(base_c*4, base_c*8, stride=2)
        self.down4 = qat_conv_block(base_c*8, base_c*16, stride=2)
        self.bottleneck = qat_conv_block(base_c*16, base_c*32, stride=2)

        self.upsample = nn.Upsample(scale_factor=2, mode='nearest')

        self.up1 = qat_conv_block(base_c*32 + base_c*16, base_c*16)
        self.up2 = qat_conv_block(base_c*16 + base_c*8, base_c*8)
        self.up3 = qat_conv_block(base_c*8 + base_c*4, base_c*4)
        self.up4 = qat_conv_block(base_c*4 + base_c*2, base_c*2)
        self.up5 = qat_conv_block(base_c*2 + base_c, base_c)

        self.tail_conv = nn.Conv2d(base_c, 3, kernel_size=1, bias=True)
        self.tanh = nn.Tanh()

    def forward(self, x_stego):
        # Quantize Input cho Decoder
        x_stego = qat_quant(x_stego)

        c1 = self.head(x_stego)
        c2 = self.down1(c1)
        c3 = self.down2(c2)
        c4 = self.down3(c3)
        c5 = self.down4(c4)
        b  = self.bottleneck(c5)

        u1 = self.up1(torch.cat([self.upsample(b), c5], dim=1))
        u2 = self.up2(torch.cat([self.upsample(u1), c4], dim=1))
        u3 = self.up3(torch.cat([self.upsample(u2), c3], dim=1))
        u4 = self.up4(torch.cat([self.upsample(u3), c2], dim=1))
        u5 = self.up5(torch.cat([self.upsample(u4), c1], dim=1))

        # Quantize Weight & Bias lớp cuối
        w_tail = qat_quant(self.tail_conv.weight)
        b_tail = qat_quant(self.tail_conv.bias)
        out = F.conv2d(u5, w_tail, b_tail, stride=1)

        return self.tanh(out) # Output cuối cùng có thể không cần quantize nếu chỉ để view

# ==============================================================================
# 3. DISCRIMINATOR (FLOAT32 - GIỮ NGUYÊN)
# ==============================================================================
# Chúng ta giữ nguyên Discriminator ở Float32 để nó "chấm thi" khó nhất có thể.

class Type1ResBlock(nn.Module):
    def __init__(self, in_c, out_c):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_c, out_c, 3, 1, 1, bias=False), nn.BatchNorm2d(out_c), nn.ReLU(True),
            nn.Conv2d(out_c, out_c, 3, 1, 1, bias=False), nn.BatchNorm2d(out_c)
        )
        self.shortcut = nn.Sequential()
        if in_c != out_c: self.shortcut = nn.Conv2d(in_c, out_c, 1, 1, 0, bias=False)
    def forward(self, x): return x + self.conv(x)

class Type2ResBlock(nn.Module):
    def __init__(self, in_c, out_c):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_c, out_c, 3, 1, 1, bias=False), nn.BatchNorm2d(out_c), nn.ReLU(True),
            nn.Conv2d(out_c, out_c, 3, 1, 1, bias=False), nn.BatchNorm2d(out_c), nn.AvgPool2d(3, 2, 1)
        )
        self.shortcut = nn.Sequential(
            nn.Conv2d(in_c, out_c, 1, 1, 0, bias=False), nn.BatchNorm2d(out_c), nn.AvgPool2d(3, 2, 1)
        )
    def forward(self, x): return self.shortcut(x) + self.conv(x)

class Type3Block(nn.Module):
    def __init__(self, in_c, out_c):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_c, out_c, 3, 1, 1, bias=False), nn.BatchNorm2d(out_c), nn.ReLU(True), nn.AvgPool2d(3, 2, 1)
        )
        self.shortcut = nn.Sequential(
            nn.Conv2d(in_c, out_c, 1, 1, 0, bias=False), nn.BatchNorm2d(out_c), nn.AvgPool2d(3, 2, 1)
        )
    def forward(self, x): return self.shortcut(x) + self.conv(x)

class SRNetDiscriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Conv2d(3, 16, 3, 1, 1, bias=False)
        self.layer2 = Type1ResBlock(16, 16)
        self.layer3 = Type2ResBlock(16, 32)
        self.layer4 = Type2ResBlock(32, 64)
        self.layer5 = Type2ResBlock(64, 64)
        self.layer6 = Type3Block(64, 64)
        self.fc = nn.Linear(64, 1)
    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.layer5(x)
        x = self.layer6(x)
        x = x.mean(dim=[2, 3])
        return self.fc(x)

# ==============================================================================
# 4. DATA & UTILS
# ==============================================================================
from torchmetrics.image.psnr import PeakSignalNoiseRatio
from torchmetrics.image.ssim import StructuralSimilarityIndexMeasure

class RealImageDataset(Dataset):
    def __init__(self, real_dir, img_size=128):
        try: self.paths = [os.path.join(real_dir, f) for f in os.listdir(real_dir) if f.lower().endswith(('png','jpg','jpeg'))]
        except: self.paths = []
        self.t = transforms.Compose([transforms.Resize((img_size, img_size)), transforms.ToTensor(), transforms.Normalize([0.5]*3,[0.5]*3)])
    def __len__(self): return len(self.paths)
    def __getitem__(self, i):
        try: return self.t(Image.open(self.paths[i]).convert("RGB"))
        except: return torch.zeros(3, 128, 128)

def get_loaders(cfg):
    dl_train = DataLoader(RealImageDataset(cfg.TRAIN_REAL_DIR, cfg.IMG_SIZE), batch_size=cfg.BATCH_SIZE, shuffle=True, num_workers=2, drop_last=True)
    dl_val = DataLoader(RealImageDataset(cfg.VAL_REAL_DIR, cfg.IMG_SIZE), batch_size=cfg.BATCH_SIZE, shuffle=False, num_workers=2, drop_last=True)
    return dl_train, dl_val

psnr_fn = PeakSignalNoiseRatio(data_range=1.0).to(Config.DEVICE)
ssim_fn = StructuralSimilarityIndexMeasure(data_range=1.0).to(Config.DEVICE)

def calc_metrics(i1, i2):
    i1, i2 = ((i1+1)/2).clamp(0,1), ((i2+1)/2).clamp(0,1)
    return psnr_fn(i1, i2).item(), ssim_fn(i1, i2).item()

def denorm(t): return ((t+1)/2).clamp(0,1).cpu().permute(0,2,3,1).numpy()

def train_step(models, optims, losses, data, cfg):
    enc, dec, disc = models
    opt_G, opt_D = optims
    l1, l2, bce, lpips_fn = losses
    cover, secret = data

    # --- Train D (Float32) ---
    opt_D.zero_grad()
    pred_real = disc(cover)
    loss_real = bce(pred_real, torch.ones_like(pred_real) * 0.9)

    with torch.no_grad(): stego = enc(cover, secret) # Encoder tạo ảnh Stego (bị nhiễu Q6.10)
    pred_stego = disc(stego)
    loss_stego = bce(pred_stego, torch.zeros_like(pred_stego))

    loss_D = (loss_real + loss_stego) * 0.5
    loss_D.backward(); opt_D.step()

    with torch.no_grad():
        d_acc = ((torch.sigmoid(pred_real)>0.5).float().mean() + (torch.sigmoid(pred_stego)<0.5).float().mean()) / 2

    # --- Train G (QAT Models) ---
    opt_G.zero_grad()
    stego = enc(cover, secret)
    rev = dec(stego)

    l_c = cfg.LAMBDA_COVER_L1*l1(stego, cover) + cfg.LAMBDA_COVER_L2*l2(stego, cover) + cfg.LAMBDA_COVER_LPIPS*lpips_fn(stego, cover).mean()
    l_s = cfg.LAMBDA_SECRET * l1(rev, secret)
    l_adv = cfg.LAMBDA_ADV * bce(disc(stego), torch.ones_like(pred_stego))

    loss_G = l_c + l_s + l_adv
    loss_G.backward(); opt_G.step()

    return loss_D.item(), {'Loss_G': loss_G.item(), 'Cov': l_c.item(), 'Sec': l_s.item(), 'Adv': l_adv.item(), 'D_Acc': d_acc.item()}

def run_validation(models, loader, cfg, epoch):
    enc, dec, disc = models
    enc.eval(); dec.eval()
    acc = {'Cov':0, 'Sec':0, 'PSNR_C':0, 'SSIM_C':0, 'PSNR_S':0, 'SSIM_S':0}
    cnt = 0
    with torch.no_grad():
        for cover in loader:
            cover = cover.to(cfg.DEVICE)
            secret = cover[torch.randperm(cover.size(0))].to(cfg.DEVICE)
            stego = enc(cover, secret)
            rev = dec(stego)

            acc['Cov'] += nn.L1Loss()(stego, cover).item()
            acc['Sec'] += nn.L1Loss()(rev, secret).item()
            pc, sc = calc_metrics(stego, cover)
            ps, ss = calc_metrics(rev, secret)
            acc['PSNR_C'] += pc; acc['SSIM_C'] += sc
            acc['PSNR_S'] += ps; acc['SSIM_S'] += ss
            cnt += 1

    res = {k: v/cnt for k, v in acc.items()}

    # Visualization
    c = next(iter(loader)).to(cfg.DEVICE)[:3]
    s = c[torch.randperm(c.size(0))].to(cfg.DEVICE)
    with torch.no_grad():
        st, re = enc(c, s), dec(enc(c, s))
        diff = torch.abs(st - c)
        diff = (diff - diff.min()) / (diff.max() - diff.min() + 1e-8)

    imgs = [denorm(c), denorm(s), denorm(st), denorm(diff), denorm(re)]
    titles = ["Cover", "Secret", "Stego", "Residual", "Revealed"]
    fig, axes = plt.subplots(3, 5, figsize=(15, 9))
    for i in range(3):
        for j in range(5):
            img_show = imgs[j][i]
            if j == 3: img_show = img_show.mean(2)
            axes[i,j].imshow(img_show, cmap='inferno' if j==3 else None)
            if i==0: axes[i,j].set_title(titles[j])
            axes[i,j].axis('off')
    plt.tight_layout()
    plt.savefig(os.path.join(cfg.SAVE_DIR, f"qat_vis_epoch_{epoch}.png"))
    plt.close()
    return res

def plot_training_history(history, cfg, epoch):
    if len(history['val_psnr_c']) == 0: return
    ep_range = range(1, len(history['train_loss_g']) + 1)
    if len(ep_range) != len(history['val_psnr_c']):
        min_len = min(len(ep_range), len(history['val_psnr_c']))
        ep_range = range(1, min_len + 1)

    fig, ax = plt.subplots(2, 3, figsize=(20, 10))
    fig.suptitle(f'QAT Training Progress - Epoch {epoch}', fontsize=16)

    ax[0,0].plot(ep_range, history['train_loss_g'][:len(ep_range)], label='G', color='b')
    ax[0,0].plot(ep_range, history['train_loss_d'][:len(ep_range)], label='D', color='r')
    ax[0,0].legend(); ax[0,0].set_title('Losses')

    ax[0,1].plot(ep_range, history['train_cov'][:len(ep_range)], label='Cov')
    ax[0,1].plot(ep_range, history['train_sec'][:len(ep_range)], label='Sec')
    ax[0,1].legend(); ax[0,1].set_title('G Components')

    ax[0,2].plot(ep_range, history['train_d_acc'][:len(ep_range)], label='D Acc')
    ax[0,2].set_title('D Accuracy')

    ax[1,0].plot(ep_range, history['val_psnr_c'][:len(ep_range)], label='Cov')
    ax[1,0].plot(ep_range, history['val_psnr_s'][:len(ep_range)], label='Sec')
    ax[1,0].set_title('PSNR')

    ax[1,1].plot(ep_range, history['val_ssim_c'][:len(ep_range)], label='Cov')
    ax[1,1].plot(ep_range, history['val_ssim_s'][:len(ep_range)], label='Sec')
    ax[1,1].set_title('SSIM')

    plt.tight_layout()
    plt.savefig(os.path.join(cfg.SAVE_DIR, "qat_history.png"))
    plt.close()

# ==============================================================================
# 5. MAIN PROGRAM (FINE-TUNING)
# ==============================================================================
def main():
    cfg = Config()
    dl_train, dl_val = get_loaders(cfg)
    if len(dl_train) == 0: return print("Lỗi Data")

    # 1. Khởi tạo QAT Models
    print("Khởi tạo QATEncoder và QATDecoder (Q6.10)...")
    enc_qat = QATEncoder(base_c=cfg.BASE_CHANNEL).to(cfg.DEVICE)
    dec_qat = QATDecoder(base_c=cfg.BASE_CHANNEL).to(cfg.DEVICE)

    # Discriminator giữ nguyên Float32
    disc = SRNetDiscriminator().to(cfg.DEVICE)

    # 2. LOAD PRETRAINED WEIGHTS (QUAN TRỌNG)
    print("Loading Pretrained Float32 Weights...")
    try:
        # Load weights cũ vào cấu trúc mới
        # Do tên biến self.depthwise, self.pointwise giống hệt nhau nên load được
        # strict=False để bỏ qua các lớp QuantIdentity không có tham số
        enc_qat.load_state_dict(torch.load(os.path.join(cfg.DRIVE_PATH, "best_enc.pth")), strict=False)
        dec_qat.load_state_dict(torch.load(os.path.join(cfg.DRIVE_PATH, "best_dec.pth")), strict=False)

        # Load Discriminator (nếu có file checkpoint chung, không thì khởi tạo lại cũng được)
        ckpt_path = os.path.join(cfg.DRIVE_PATH, "checkpoint.pth")
        if os.path.exists(ckpt_path):
            c = torch.load(ckpt_path)
            disc.load_state_dict(c['disc'])
            print("Loaded Discriminator checkpoint.")
        else:
            print("Không tìm thấy Discriminator checkpoint, train D từ đầu.")

    except Exception as e:
        print(f"Lỗi load weights: {e}")
        print("DỪNG LẠI! QAT cần pretrained weights để hội tụ.")
        return

    # 3. Optimizers với Learning Rate THẤP
    opt_G = optim.Adam(list(enc_qat.parameters())+list(dec_qat.parameters()), lr=cfg.LEARNING_RATE, betas=(0.5, 0.999))
    opt_D = optim.Adam(disc.parameters(), lr=cfg.LEARNING_RATE_DISC, betas=(0.5, 0.999))
    losses = [nn.L1Loss(), nn.MSELoss(), nn.BCEWithLogitsLoss(), lpips.LPIPS(net='alex').to(cfg.DEVICE)]

    history = {'train_loss_g': [], 'train_loss_d': [], 'train_cov': [], 'train_sec': [], 'train_adv': [], 'train_d_acc': [],
               'val_psnr_c': [], 'val_ssim_c': [], 'val_psnr_s': [], 'val_ssim_s': []}

    best_score = float('inf')

    print(f"\n BẮT ĐẦU QAT FINE-TUNING (Epoch 1 -> {cfg.NUM_EPOCHS})")

    for epoch in range(1, cfg.NUM_EPOCHS + 1):
        # Bật chế độ Train (để FakeQuantize hoạt động)
        enc_qat.train(); dec_qat.train(); disc.train()

        t0 = time.time()
        running_results = {'Loss_D': 0, 'Loss_G': 0, 'Cov': 0, 'Sec': 0, 'Adv': 0, 'D_Acc': 0}

        for idx, cover in enumerate(dl_train):
            cover = cover.to(cfg.DEVICE)
            secret = cover[torch.randperm(cover.size(0))].to(cfg.DEVICE)

            # Train Step (Input sẽ tự động được Quantize trong Forward của Encoder)
            l_d, m = train_step((enc_qat, dec_qat, disc), (opt_G, opt_D), losses, (cover, secret), cfg)

            running_results['Loss_D'] += l_d
            for k, v in m.items(): running_results[k] += v

            if idx % 100 == 0:
                print(f"QAT Ep{epoch} B{idx}: Loss_G={m['Loss_G']:.3f} | Cov={m['Cov']:.3f}")

        # Log History
        for k in running_results: running_results[k] /= len(dl_train)
        history['train_loss_g'].append(running_results['Loss_G'])
        history['train_loss_d'].append(running_results['Loss_D'])
        history['train_cov'].append(running_results['Cov'])
        history['train_sec'].append(running_results['Sec'])
        history['train_adv'].append(running_results['Adv'])
        history['train_d_acc'].append(running_results['D_Acc'])

        # Validation
        print(f">>> Validating QAT...")
        res = run_validation((enc_qat, dec_qat, disc), dl_val, cfg, epoch)

        history['val_psnr_c'].append(res['PSNR_C'])
        history['val_ssim_c'].append(res['SSIM_C'])
        history['val_psnr_s'].append(res['PSNR_S'])
        history['val_ssim_s'].append(res['SSIM_S'])

        score = res['Cov'] + res['Sec']
        print(f"    [QAT VAL] Score: {score:.4f} | Cov PSNR: {res['PSNR_C']:.2f} | Sec PSNR: {res['PSNR_S']:.2f}")

        plot_training_history(history, cfg, epoch)


        save_dict = {
            'epoch': epoch,
            'enc': enc_qat.state_dict(),
            'dec': dec_qat.state_dict(),
            'disc': disc.state_dict(),
            'hist': history
        }
        torch.save(save_dict, os.path.join(Config.SAVE_DIR, "qat_checkpoint.pth"))

        # Save Checkpoint QAT
        if score < best_score:
            print("NEW QAT BEST! Saving...")
            best_score = score
            torch.save(enc_qat.state_dict(), os.path.join(cfg.SAVE_DIR, "best_enc_qat_q6_10.pth"))
            torch.save(dec_qat.state_dict(), os.path.join(cfg.SAVE_DIR, "best_dec_qat_q6_10.pth"))

        print(f"--- Done Epoch {epoch} ({time.time()-t0:.1f}s) ---\n")

        # 3. Lưu ảnh Visualization (Để so sánh chất lượng mắt nhìn)
        # Tên file sẽ là: qat_vis_epoch_1.png, qat_vis_epoch_2.png...
        plt.savefig(os.path.join(Config.SAVE_DIR, f"qat_vis_epoch_{epoch}.png"))

        # 4. Lưu đồ thị History (Loss/PSNR/SSIM)
        plt.savefig(os.path.join(Config.SAVE_DIR, "qat_training_history.png"))

if __name__ == "__main__":
    main()

import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image
import os
import matplotlib.pyplot as plt
import numpy as np

# ==============================================================================
# 1. THIẾT LẬP ĐƯỜNG DẪN & CONFIG
# ==============================================================================

QAT_DIR = "/content/drive/MyDrive/final/final1/qat_results_q6_10"
ENC_QAT_PATH = os.path.join(QAT_DIR, "best_enc_qat_q6_10.pth")
DEC_QAT_PATH = os.path.join(QAT_DIR, "best_dec_qat_q6_10.pth")
OUTPUT_IMAGE_PATH = os.path.join(QAT_DIR, "final_qat_comparison.png")

# Đảm bảo dùng đúng thiết bị
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==============================================================================
# 2. LOAD LẠI CẤU TRÚC MODEL QAT (Bắt buộc phải giống lúc train)
# ==============================================================================
# Lưu ý: Bạn cần đảm bảo các lớp FakeQuantizeQ6_10, QATSeparableConv2d,
# QATEncoder, QATDecoder đã được định nghĩa ở các ô trước đó.

def load_qat_models():
    enc = QATEncoder(base_c=32).to(device)
    dec = QATDecoder(base_c=32).to(device)

    # Load trọng số
    enc.load_state_dict(torch.load(ENC_QAT_PATH, map_location=device))
    dec.load_state_dict(torch.load(DEC_QAT_PATH, map_location=device))

    enc.eval()
    dec.eval()
    print("✅ Đã load thành công Encoder & Decoder QAT 16-bit.")
    return enc, dec

# ==============================================================================
# 3. HÀM XỬ LÝ ẢNH & INFERENCE
# ==============================================================================
def denormalize(t):
    return ((t + 1) / 2).clamp(0, 1).cpu().permute(0, 2, 3, 1).numpy()

def generate_comparison_images(enc, dec, num_samples=3):
    # Lấy dữ liệu từ Val Loader (hoặc tạo giả lập nếu không có loader)
    cfg = Config()
    _, dl_val = get_loaders(cfg)
    cover_batch = next(iter(dl_val)).to(device)
    # Tạo secret bằng cách xáo trộn batch
    secret_batch = cover_batch[torch.randperm(cover_batch.size(0))].to(device)

    with torch.no_grad():
        # Bước cực kỳ quan trọng: Mô phỏng ảnh đầu vào 16-bit Q6.10
        # Mặc dù trong forward của model đã có, ta thực hiện ở đây để tường minh
        c = qat_quant(cover_batch[:num_samples])
        s = qat_quant(secret_batch[:num_samples])

        # Chạy model
        stego = enc(c, s)
        revealed = dec(stego)

        # Tính sai số (Residual) - Nhân 10 để nhìn rõ hơn
        residual = torch.abs(stego - c)
        residual = (residual - residual.min()) / (residual.max() - residual.min() + 1e-8)

    # Chuyển đổi về numpy để vẽ
    c_np = denormalize(c)
    s_np = denormalize(s)
    st_np = denormalize(stego)
    res_np = denormalize(residual)
    rev_np = denormalize(revealed)

    # Vẽ biểu đồ so sánh
    titles = ["Cover", "Secret", "Stego (QAT)", "Residual (x10)", "Revealed (QAT)"]
    fig, axes = plt.subplots(num_samples, 5, figsize=(18, 10))

    for i in range(num_samples):
        imgs = [c_np[i], s_np[i], st_np[i], res_np[i], rev_np[i]]
        for j in range(5):
            ax = axes[i, j]
            if j == 3: # Residual vẽ Heatmap cho dễ nhìn
                ax.imshow(imgs[j].mean(axis=2), cmap='inferno')
            else:
                ax.imshow(imgs[j])

            if i == 0:
                ax.set_title(titles[j], fontweight='bold', fontsize=12)
            ax.axis('off')

    plt.tight_layout()
    plt.savefig(OUTPUT_IMAGE_PATH)
    plt.show()
    print(f" Đã lưu ảnh so sánh tại: {OUTPUT_IMAGE_PATH}")

# Thực thi
enc_qat, dec_qat = load_qat_models()
generate_comparison_images(enc_qat, dec_qat)

import os
import shutil
from google.colab import drive

# 1. Thử unmount trước để an toàn
try:
    drive.flush_and_unmount()
    print("Đã unmount thành công.")
except Exception as e:
    print(f"Chưa mount hoặc lỗi unmount: {e}")

# 2. Xóa thư mục /content/drive nếu nó đang tồn tại và chứa file rác
if os.path.exists('/content/drive'):
    print("Phát hiện thư mục cũ, đang xóa...")
    shutil.rmtree('/content/drive')

# 3. Mount lại với tham số force_remount
print("Đang kết nối lại Google Drive...")
drive.mount('/content/drive', force_remount=True)

import torch
import numpy as np
import os


# ==============================================================================
# 1. CẤU HÌNH ĐƯỜNG DẪN
# ==============================================================================
# Đường dẫn chứa file model đã train xong
INPUT_MODEL_PATH = "/content/drive/MyDrive/final/final1/qat_results_q6_10/best_enc_qat_q6_10.pth"

# Thư mục chứa các file .mem sẽ xuất ra
OUTPUT_HEX_DIR = "/content/drive/MyDrive/final/final1/qat_results_q6_10/fpga_hex_files"
os.makedirs(OUTPUT_HEX_DIR, exist_ok=True)

# ==============================================================================
# 2. HÀM CHUYỂN ĐỔI & GHI FILE HEX
# ==============================================================================
def export_tensor_to_hex(tensor_name, tensor_data, output_dir):
    """
    Input:
       - tensor_name: Tên lớp (ví dụ: head.0.depthwise.weight)
       - tensor_data: Dữ liệu Float32
    Output:
       - File .mem chứa mã Hex Q6.10
    """
    # 1. Chuyển sang Numpy
    data_float = tensor_data.detach().cpu().numpy()

    # 2. Toán tử Q6.10: Nhân 1024 và làm tròn
    # Ép sang int16 để mô phỏng đúng giới hạn lưu trữ
    data_int16 = np.round(data_float * 1024).astype(np.int16)

    # 3. Tạo tên file an toàn
    safe_name = tensor_name.replace(".", "_") + ".mem"
    file_path = os.path.join(output_dir, safe_name)

    # 4. Ghi file Hex
    with open(file_path, "w") as f:
        for val in data_int16.flatten():
            val_python = int(val)
            f.write(f"{val_python & 0xFFFF:04x}\n")

    print(f"   Saved: {safe_name} \t(Size: {data_int16.size})")

# ==============================================================================
# 3. CHƯƠNG TRÌNH CHÍNH
# ==============================================================================
def main_export():
    device = torch.device("cpu") # Xuất file thì dùng CPU cho đơn giản

    print(f"--- BẮT ĐẦU XUẤT FILE HEX Q6.10 ---")
    print(f"Input: {INPUT_MODEL_PATH}")
    print(f"Output: {OUTPUT_HEX_DIR}\n")

    # B1: Khởi tạo lại Model (Cần class QATEncoder đã định nghĩa ở các cell trước)
    try:
        model = QATEncoder(base_c=32).to(device)
    except NameError:
        print("LỖI: chưa chạy cell định nghĩa class 'QATEncoder'.")
        return

    # B2: Load trọng số từ file .pth
    if not os.path.exists(INPUT_MODEL_PATH):
        print(f"LỖI: Không tìm thấy file {INPUT_MODEL_PATH}")
        return

    state_dict = torch.load(INPUT_MODEL_PATH, map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    # B3: Duyệt qua toàn bộ trọng số (Weights) và Bias (nếu có)
    # Chúng ta dùng model.state_dict() để lấy cả Weights và Running Stats của BatchNorm
    count = 0
    for key, value in model.state_dict().items():
        # Chỉ xuất các tensor có dữ liệu (bỏ qua các biến đếm num_batches_tracked của BN)
        if "num_batches_tracked" in key:
            continue

        export_tensor_to_hex(key, value, OUTPUT_HEX_DIR)
        count += 1

    print(f"\nĐÃ HOÀN TẤT! Tổng cộng {count} file .mem đã được lưu.")
    print(f"Kiểm tra tại thư mục Drive: {OUTPUT_HEX_DIR}")

    # B4: (Tùy chọn) Kiểm tra thử 1 giá trị để yên tâm
    # Lấy thử 1 giá trị đầu tiên của lớp đầu tiên
    first_key = list(model.state_dict().keys())[0]
    val_float = model.state_dict()[first_key].flatten()[0].item()
    val_int = int(round(val_float * 1024))
    val_hex = val_int & 0xFFFF
    print(f"\n KIỂM TRA MẪU ({first_key}):")
    print(f"   - Float gốc: {val_float:.6f}")
    print(f"   - Int16 (x1024): {val_int}")
    print(f"   - Hex File: {val_hex:04x}")

if __name__ == "__main__":
    main_export()

import os
import shutil
from google.colab import drive

print("🛠️ Đang khắc phục lỗi mount...")

# 1. Cố gắng unmount trước (đề phòng đang mount dở)
try:
    drive.flush_and_unmount()
    print("   -> Đã gửi lệnh unmount.")
except Exception as e:
    print(f"   -> Thông báo unmount (có thể bỏ qua): {e}")

# 2. Xóa triệt để thư mục /content/drive nếu nó vẫn tồn tại
# Đây là bước quan trọng nhất để sửa lỗi "Mountpoint must not already contain files"
if os.path.exists('/content/drive'):
    print("   -> Phát hiện thư mục /content/drive cũ, đang xóa...")
    try:
        shutil.rmtree('/content/drive')
        print("   -> Đã xóa thư mục cũ thành công.")
    except OSError as e:
        print(f"   -> Lỗi khi xóa (thường do hệ thống file đang bận): {e}")

# 3. Mount lại với force_remount=True
print("🔄 Đang kết nối lại Google Drive...")
try:
    drive.mount('/content/drive', force_remount=True)
    print("✅ Kết nối Google Drive THÀNH CÔNG!")
except Exception as e:
    print(f"❌ Vẫn gặp lỗi: {e}")
    print("Gợi ý: Hãy thử khởi động lại Runtime (Runtime -> Restart Session) rồi chạy lại ô này.")

import torch
import torch.nn as nn
import numpy as np
import os
import math




# ==============================================================================
# 1. CÁC HÀM TIỆN ÍCH (UTILS) - GIỮ NGUYÊN
# ==============================================================================
# (Copy lại phần Fuse Model từ code trước của bạn để đảm bảo tính nhất quán)
def fuse_conv_bn_weights(conv, bn):
    with torch.no_grad():
        mean, var_sqrt = bn.running_mean, torch.sqrt(bn.running_var + bn.eps)
        gamma, beta = bn.weight, bn.bias
        w_conv = conv.weight.clone()
        b_conv = conv.bias.clone() if conv.bias is not None else torch.zeros_like(mean)

        scale = (gamma / var_sqrt).view(-1, 1, 1, 1)
        return w_conv * scale, beta + (b_conv - mean) * (gamma / var_sqrt)

def fuse_model_qat(model):
    print(">>> Đang Fuse BN vào Conv...")
    for m in model.modules():
        if isinstance(m, nn.Sequential) and len(m)>=2:
            if isinstance(m[0], QATSeparableConv2d) and isinstance(m[1], nn.BatchNorm2d):
                fw, fb = fuse_conv_bn_weights(m[0].pointwise, m[1])
                m[0].pointwise = nn.Conv2d(m[0].pointwise.in_channels, m[0].pointwise.out_channels, 1, 1, 0, bias=True)
                m[0].pointwise.weight.data.copy_(fw)
                m[0].pointwise.bias.data.copy_(fb)
                m[1] = nn.Identity()
    return model

# ==============================================================================
# 2. HÀM XUẤT MEMORY (HEX) VÀ TẠO MAP
# ==============================================================================

def float_to_hex_str(tensor_data, scale=1024.0):
    """Chuyển Tensor Float sang List các chuỗi Hex 16-bit"""
    arr = tensor_data.detach().cpu().numpy().flatten()
    arr_int = np.round(arr * scale).astype(np.int32)
    # Kẹp giá trị trong miền 16-bit có dấu
    arr_int = np.clip(arr_int, -32768, 32767)

    hex_lines = []
    for val in arr_int:
        # Format 4 ký tự hex (16-bit), xử lý số âm bằng mask 0xFFFF
        hex_lines.append(f"{val & 0xFFFF:04x}")
    return hex_lines

def export_mem_files_with_map(model, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    dw_path = os.path.join(output_dir, "depthwise.mem")
    pw_path = os.path.join(output_dir, "pointwise.mem")

    # Bộ đếm địa chỉ (Word Address - mỗi dòng là 1 từ 16-bit)
    addr_dw = 0
    addr_pw = 0

    map_info = [] # Lưu thông tin để in ra bảng Map

    print(f"\n>>> BẮT ĐẦU XUẤT FILE .MEM TẠI: {output_dir}")

    with open(dw_path, "w") as f_dw, open(pw_path, "w") as f_pw:

        # Cờ đặc biệt cho Layer đầu tiên
        is_head_layer = True

        for name, module in model.named_modules():
            # --- XỬ LÝ DEPTHWISE ---
            if isinstance(module, nn.Conv2d) and module.groups > 1:
                # 1. Lấy dữ liệu Weight
                hex_data = float_to_hex_str(module.weight)
                count = len(hex_data)

                # 2. Ghi vào file
                f_dw.write('\n'.join(hex_data) + '\n')

                # 3. Lưu thông tin Map
                map_info.append({
                    "type": "DW", "name": name,
                    "start": addr_dw, "count": count,
                    "shape": tuple(module.weight.shape)
                })
                addr_dw += count

                # 4. Xử lý Chèn Rác (Alignment) cho HEAD Layer
                if is_head_layer:
                    # Chèn 2 từ 16-bit (tương ứng 32-bit 0xDEADBEEF)
                    f_dw.write("dead\nbeef\n")
                    print(f"   [ALIGN] Chèn 0xDEADBEEF sau {name} tại địa chỉ {addr_dw}")
                    addr_dw += 2
                    is_head_layer = False

            # --- XỬ LÝ POINTWISE (Weight + Bias liền nhau) ---
            elif isinstance(module, nn.Conv2d) and module.kernel_size == (1, 1):
                # 1. Weight
                w_hex = float_to_hex_str(module.weight)
                w_count = len(w_hex)
                f_pw.write('\n'.join(w_hex) + '\n')

                # 2. Bias (Pointwise luôn có bias sau khi fuse)
                if module.bias is not None:
                    b_hex = float_to_hex_str(module.bias)
                    b_count = len(b_hex)
                    f_pw.write('\n'.join(b_hex) + '\n')
                else:
                    b_hex = []; b_count = 0
                    print(f"   [WARNING] {name} không có bias!")

                # 3. Lưu Map (Ghi chú rõ phần Weight và Bias nằm liền nhau)
                total_count = w_count + b_count
                map_info.append({
                    "type": "PW", "name": name,
                    "start": addr_pw, "count": total_count,
                    "w_shape": tuple(module.weight.shape),
                    "note": f"Weights: {w_count} words, Bias: {b_count} words"
                })
                addr_pw += total_count

    # --- IN BẢNG ĐỊA CHỈ (MEMORY MAP) ---
    print("\n" + "="*80)
    print(f"{'TYPE':<5} | {'LAYER NAME':<35} | {'START (Hex)':<10} | {'SIZE (Dec)':<10} | {'DETAILS'}")
    print("-" * 80)

    for item in map_info:
        start_hex = f"0x{item['start']:04X}"
        if item['type'] == 'DW':
            desc = f"Shape {item['shape']}"
        else:
            desc = item['note']

        print(f"{item['type']:<5} | {item['name']:<35} | {start_hex:<10} | {item['count']:<10} | {desc}")
    print("="*80 + "\n")

# ==============================================================================
# 3. CHẠY CHƯƠNG TRÌNH
# ==============================================================================
if __name__ == "__main__":
    # 1. Setup
    device = torch.device("cpu")
    model = QATEncoder(base_c=32).to(device)
    path = "/content/drive/MyDrive/final/final1/qat_results_q6_10/best_enc_qat_q6_10.pth"

    # 2. Load & Fuse
    if os.path.exists(path):
        model.load_state_dict(torch.load(path, map_location=device))
        model.eval()
        model = fuse_model_qat(model)

        # 3. Export
        out_dir = "/content/drive/MyDrive/final/final1/fpga_mem_files"
        export_mem_files_with_map(model, out_dir)
    else:
        print("Không tìm thấy file model.")

"""#GOLDEN MODEL"""

import os
import torch
import torch.nn as nn
import numpy as np
from PIL import Image
import torchvision.transforms as transforms
import torchvision.utils as vutils # <-- Dùng để lưu ảnh dễ dàng

# ==============================
# 1. CONFIG (CẤU HÌNH ĐƯỜNG DẪN)
# ==============================
#TRAIN_DIR = "/root/.cache/kagglehub/datasets/xhlulu/140k-real-and-fake-faces/versions/2/real_vs_fake/real-vs-fake/train/real"
TRAIN_DIR = "/kaggle/input/140k-real-and-fake-faces/real_vs_fake/real-vs-fake/train/real"
ENC_MODEL_PATH = "/content/drive/MyDrive/final/final1/qat_results_q6_10/best_enc_qat_q6_10.pth"

# BỔ SUNG: Đường dẫn đến trọng số của Decoder (Bạn hãy sửa lại cho đúng tên file của bạn)
DEC_MODEL_PATH = "/content/drive/MyDrive/final/final1/qat_results_q6_10/best_dec_qat_q6_10.pth"

OUTPUT_DIR = "/content/drive/MyDrive/final/final1/golden_output"
IMAGE_OUT_DIR = "/content/drive/MyDrive/final/final1/verify_images" # Thư mục lưu ảnh PNG

Q_FRAC = 10
Q_SCALE = 2 ** Q_FRAC         # 1024.0
INT16_MIN = -32768
INT16_MAX = 32767

# ==============================
# 2. FLOAT → Q6.10
# ==============================
def float_to_q6_10(x):
    """Lượng tử hóa Q6.10, kẹp biên 16-bit signed"""
    x_scaled = torch.round(x * Q_SCALE)
    x_clamped = torch.clamp(x_scaled, INT16_MIN, INT16_MAX)
    return x_clamped.to(torch.int16)

# ==============================
# 3. SAVE HEX FILE
# ==============================
def save_hex(tensor, filename):
    """Lưu tensor int16 ra file hex chuẩn bù 2 (Tối ưu bằng Numpy)"""
    arr = tensor.contiguous().view(-1).numpy().astype(np.int32)
    with open(filename, "w") as f:
        for val in arr:
            f.write(f"{val & 0xFFFF:04x}\n")

# ==============================
# 4. REGISTER HOOKS
# ==============================
def register_hooks(model, layer_outputs):
    def hook_fn(name):
        def hook(module, input, output):
            layer_outputs[name] = output.detach().cpu()
        return hook

    target_classes = [
        'Conv2d', 'ReLU', 'Linear',
        'MaxPool2d', 'AvgPool2d', 'Tanh',
        'QATSeparableConv2d'
    ]
    for name, module in model.named_modules():
        class_name = module.__class__.__name__
        if class_name in target_classes:
            safe_name = name.replace('.', '_')
            module.register_forward_hook(hook_fn(safe_name))

# ==============================
# 5. MAIN
# ==============================
def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(IMAGE_OUT_DIR, exist_ok=True)
    device = torch.device("cpu")

    # ---------------------------------------------------------
    # BƯỚC 1: LOAD MODEL ENCODER & DECODER
    # ---------------------------------------------------------
    print(f">>> Loading ENCODER from {ENC_MODEL_PATH}...")
    try:
        encoder = QATEncoder(base_c=32).to(device)
        encoder.load_state_dict(torch.load(ENC_MODEL_PATH, map_location=device))
        encoder.eval()
        print(" Load ENCODER thành công!")
    except Exception as e:
        print(f"⚠ LỖI ENCODER: {e}. (Sẽ dùng Random Weights để test)")
        encoder = QATEncoder(base_c=32).to(device).eval()

    print(f">>> Loading DECODER from {DEC_MODEL_PATH}...")
    try:
        # Nhớ định nghĩa class QATDecoder hoặc Decoder trước khi chạy!
        decoder = QATDecoder(base_c=32).to(device)
        decoder.load_state_dict(torch.load(DEC_MODEL_PATH, map_location=device))
        decoder.eval()
        print(" Load DECODER thành công!")
    except Exception as e:
        print(f" LỖI DECODER: {e}. (Chưa load được Decoder thật)")
        # Tạo hàm dummy nếu không có decoder để code không văng lỗi
        decoder = lambda x: x

    # ---------------------------------------------------------
    # BƯỚC 2: LOAD & PREPROCESS IMAGE
    # ---------------------------------------------------------
    print(f"\n>>> Loading images from {TRAIN_DIR}...")
    try:
        img_list = sorted(os.listdir(TRAIN_DIR))
        cover_path = os.path.join(TRAIN_DIR, img_list[0])
        secret_path = os.path.join(TRAIN_DIR, img_list[1])

        transform = transforms.Compose([
            transforms.Resize((128, 128)),
            transforms.ToTensor(),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)) # Đưa về [-1, 1]
        ])

        x_cover = transform(Image.open(cover_path).convert("RGB")).unsqueeze(0)
        x_secret = transform(Image.open(secret_path).convert("RGB")).unsqueeze(0)
        print(" Load ảnh thật thành công!")
    except FileNotFoundError:
        print(" Đang tạo ảnh Dummy Data để test...")
        x_cover = torch.randn(1, 3, 128, 128)
        x_secret = torch.randn(1, 3, 128, 128)

    # ---------------------------------------------------------
    # BƯỚC 3: QUANTIZE INPUT
    # ---------------------------------------------------------
    x_cover_sim = float_to_q6_10(x_cover).float() / Q_SCALE
    x_secret_sim = float_to_q6_10(x_secret).float() / Q_SCALE

    # Lưu File Hex Input
    save_hex(float_to_q6_10(x_cover), os.path.join(OUTPUT_DIR, "000_input_cover.hex"))
    save_hex(float_to_q6_10(x_secret), os.path.join(OUTPUT_DIR, "000_input_secret.hex"))

    # ---------------------------------------------------------
    # BƯỚC 4: CHẠY ENCODER & XUẤT HEX
    # ---------------------------------------------------------
    layer_outputs = {}
    register_hooks(encoder, layer_outputs)

    print("\n>>> 1. Running ENCODER Forward pass...")
    with torch.no_grad():
        # Lấy trực tiếp ảnh Stego đầu ra
        stego_output = encoder(x_cover_sim, x_secret_sim)

    # Lưu Hex các layer của Encoder
    for name, output in layer_outputs.items():
        q_out = float_to_q6_10(output)
        save_hex(q_out, os.path.join(OUTPUT_DIR, f"{name}.hex"))
    print(f" Đã xuất {len(layer_outputs)} file Hex của Encoder.")

    # ---------------------------------------------------------
    # BƯỚC 5: CHẠY DECODER ĐỂ VERIFY (KHÔI PHỤC ẢNH)
    # ---------------------------------------------------------
    print(">>> 2. Running DECODER Forward pass...")
    # CỰC KỲ QUAN TRỌNG: Ép Stego về chuẩn phần cứng Q6.10 trước khi giải mã
    # Điều này mô phỏng việc FPGA xuất ảnh Stego ra bộ nhớ rồi mới nhét vào Decoder
    stego_quantized_sim = float_to_q6_10(stego_output).float() / Q_SCALE

    with torch.no_grad():
        recovered_secret = decoder(stego_quantized_sim)

    # ---------------------------------------------------------
    # BƯỚC 6: XUẤT ẢNH RA FILE ĐỂ XEM BẰNG MẮT THƯỜNG
    # ---------------------------------------------------------
    print(f">>> 3. Saving Verification Images to {IMAGE_OUT_DIR}...")

    # Hàm con để đảo ngược quá trình Normalize (Từ [-1, 1] về [0, 1] để lưu PNG)
    def denormalize(tensor):
        return tensor * 0.5 + 0.5

    # Lưu 4 bức ảnh: Cover gốc, Secret gốc, Stego tạo ra, Secret khôi phục
    vutils.save_image(denormalize(x_cover), os.path.join(IMAGE_OUT_DIR, "1_Original_Cover.png"))
    vutils.save_image(denormalize(x_secret), os.path.join(IMAGE_OUT_DIR, "2_Original_Secret.png"))
    vutils.save_image(denormalize(stego_quantized_sim), os.path.join(IMAGE_OUT_DIR, "3_Stego_Quantized_Q6_10.png"))
    vutils.save_image(denormalize(recovered_secret), os.path.join(IMAGE_OUT_DIR, "4_Recovered_Secret.png"))

    print("\n HOÀN TẤT! Hãy mở thư mục `verify_images` để kiểm tra ảnh.")
    print("Nếu ảnh 4 (Recovered) rõ ràng và giống ảnh 2 (Original Secret), Q6.10 của bạn đã thành công rực rỡ!")

if __name__ == "__main__":
    main()

import os
import torch
import torch.nn as nn
import numpy as np
from PIL import Image
import torchvision.transforms as transforms
import torchvision.utils as vutils

# ==============================
# 1. CONFIG (CẤU HÌNH ĐƯỜNG DẪN)
# ==============================
TRAIN_DIR = "/kaggle/input/140k-real-and-fake-faces/real_vs_fake/real-vs-fake/train/real"
ENC_MODEL_PATH = "/content/drive/MyDrive/final/final1/qat_results_q6_10/best_enc_qat_q6_10.pth"
DEC_MODEL_PATH = "/content/drive/MyDrive/final/final1/qat_results_q6_10/best_dec_qat_q6_10.pth"

OUTPUT_DIR1 = "/content/drive/MyDrive/final/final1/verify/weight"
OUTPUT_DIR2 = "/content/drive/MyDrive/final/final1/verify/golden_output"
IMAGE_OUT_DIR = "/content/drive/MyDrive/final/final1/verify/verify_images"

Q_FRAC = 10
Q_SCALE = 2 ** Q_FRAC         # 1024.0
INT16_MIN = -32768
INT16_MAX = 32767

# ==============================
# 2. FLOAT → Q6.10
# ==============================
def float_to_q6_10(x):
    """Lượng tử hóa Q6.10, kẹp biên 16-bit signed"""
    x_scaled = torch.round(x * Q_SCALE)
    x_clamped = torch.clamp(x_scaled, INT16_MIN, INT16_MAX)
    return x_clamped.to(torch.int16)

# ==============================
# 3. SAVE HEX FILE
# ==============================
def save_hex(tensor, filename):
    """Lưu tensor int16 ra file hex chuẩn bù 2"""
    arr = tensor.contiguous().view(-1).numpy().astype(np.int32)
    with open(filename, "w") as f:
        for val in arr:
            f.write(f"{val & 0xFFFF:04x}\n")

# ==============================
# 4. TRÍCH XUẤT WEIGHTS & BIASES
# ==============================
def export_weights_and_biases(model, output_dir):
    """Hàm mới: Bóc tách và lưu toàn bộ Weight/Bias của mô hình"""
    print("\n" + "="*60)
    print(">>> ĐANG TRÍCH XUẤT TRỌNG SỐ (WEIGHTS & BIASES) ...")
    print("="*60)

    count_w, count_b = 0, 0

    # Duyệt qua toàn bộ các module con trong mô hình
    for name, module in model.named_modules():
        # Chỉ lấy weight/bias từ các lớp có chứa tham số tính toán
        if isinstance(module, (nn.Conv2d, nn.Linear)):
            safe_name = name.replace('.', '_')

            # 1. Lấy và lưu Weight
            if getattr(module, 'weight', None) is not None:
                w_tensor = module.weight.data
                w_q = float_to_q6_10(w_tensor)
                save_hex(w_q, os.path.join(output_dir, f"{safe_name}_weight.hex"))
                print(f"[Weight] {safe_name}_weight.hex | Shape: {list(w_q.shape)}")
                count_w += 1

            # 2. Lấy và lưu Bias (nếu có)
            if getattr(module, 'bias', None) is not None:
                b_tensor = module.bias.data
                b_q = float_to_q6_10(b_tensor)
                save_hex(b_q, os.path.join(output_dir, f"{safe_name}_bias.hex"))
                print(f"[Bias]   {safe_name}_bias.hex   | Shape: {list(b_q.shape)}")
                count_b += 1

    print(f"✅ Đã trích xuất {count_w} file Weights và {count_b} file Biases.")

# ==============================
# 5. REGISTER HOOKS CHO OUTPUT
# ==============================
def register_hooks(model, layer_outputs):
    def hook_fn(name):
        def hook(module, input, output):
            layer_outputs[name] = output.detach().cpu()
        return hook

    target_classes = [
        'Conv2d', 'ReLU', 'Linear',
        'MaxPool2d', 'AvgPool2d', 'Tanh',
        'QATSeparableConv2d'
    ]
    for name, module in model.named_modules():
        class_name = module.__class__.__name__
        if class_name in target_classes:
            safe_name = name.replace('.', '_')
            module.register_forward_hook(hook_fn(safe_name))

# ==============================
# 6. MAIN
# ==============================
def main():
    os.makedirs(OUTPUT_DIR1, exist_ok=True)
    os.makedirs(OUTPUT_DIR2, exist_ok=True)
    os.makedirs(IMAGE_OUT_DIR, exist_ok=True)
    device = torch.device("cpu")

    # ---------------------------------------------------------
    # BƯỚC 1: LOAD MODEL ENCODER & DECODER
    # ---------------------------------------------------------
    print(f">>> Loading ENCODER from {ENC_MODEL_PATH}...")
    try:
        encoder = QATEncoder(base_c=32).to(device)
        encoder.load_state_dict(torch.load(ENC_MODEL_PATH, map_location=device))
        encoder.eval()
        print(" Load ENCODER thành công!")
    except Exception as e:
        print(f" LỖI ENCODER: {e}. (Sẽ dùng Random Weights để test)")
        encoder = QATEncoder(base_c=32).to(device).eval()

    print(f">>> Loading DECODER from {DEC_MODEL_PATH}...")
    try:
        decoder = QATDecoder(base_c=32).to(device)
        decoder.load_state_dict(torch.load(DEC_MODEL_PATH, map_location=device))
        decoder.eval()
        print(" Load DECODER thành công!")
    except Exception as e:
        print(f" LỖI DECODER: {e}. (Chưa load được Decoder thật)")
        decoder = lambda x: x

    # ---------------------------------------------------------
    # BƯỚC 2: TRÍCH XUẤT WEIGHTS & BIASES CỦA ENCODER
    # ---------------------------------------------------------
    export_weights_and_biases(encoder, OUTPUT_DIR1)

    # ---------------------------------------------------------
    # BƯỚC 3: LOAD & PREPROCESS IMAGE
    # ---------------------------------------------------------
    print(f"\n>>> Loading images from {TRAIN_DIR}...")
    try:
        img_list = sorted(os.listdir(TRAIN_DIR))
        cover_path = os.path.join(TRAIN_DIR, img_list[0])
        secret_path = os.path.join(TRAIN_DIR, img_list[1])

        transform = transforms.Compose([
            transforms.Resize((128, 128)),
            transforms.ToTensor(),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
        ])

        x_cover = transform(Image.open(cover_path).convert("RGB")).unsqueeze(0)
        x_secret = transform(Image.open(secret_path).convert("RGB")).unsqueeze(0)
        print(" Load ảnh thật thành công!")
    except FileNotFoundError:
        print("⚠ Đang tạo ảnh Dummy Data để test...")
        x_cover = torch.randn(1, 3, 128, 128)
        x_secret = torch.randn(1, 3, 128, 128)

    # ---------------------------------------------------------
    # BƯỚC 4: QUANTIZE INPUT
    # ---------------------------------------------------------
    x_cover_sim = float_to_q6_10(x_cover).float() / Q_SCALE
    x_secret_sim = float_to_q6_10(x_secret).float() / Q_SCALE

    save_hex(float_to_q6_10(x_cover), os.path.join(OUTPUT_DIR2, "000_input_cover.hex"))
    save_hex(float_to_q6_10(x_secret), os.path.join(OUTPUT_DIR2, "000_input_secret.hex"))

    # ---------------------------------------------------------
    # BƯỚC 5: CHẠY ENCODER & XUẤT OUTPUT (ACTIVATIONS)
    # ---------------------------------------------------------
    layer_outputs = {}
    register_hooks(encoder, layer_outputs)

    print("\n" + "="*60)
    print(">>> ĐANG CHẠY ENCODER VÀ TRÍCH XUẤT OUTPUT (ACTIVATIONS)...")
    print("="*60)
    with torch.no_grad():
        stego_output = encoder(x_cover_sim, x_secret_sim)

    # Lưu Hex các layer của Encoder kèm thông tin chi tiết
    for name, output in layer_outputs.items():
        # Phân tích dải giá trị (Float Range)
        f_min, f_max = float(output.min()), float(output.max())

        # Kiểm tra kẹp biên 5-bit nguyên của Q6.10 (-32.0 đến 31.999)
        warning = " TRÀN SỐ!" if (f_max >= 32.0 or f_min < -32.0) else "✅ OK"

        print(f"Layer: {name:<25} | Shape: {str(list(output.shape)):<18} | Range: [{f_min:>8.4f}, {f_max:>8.4f}] | {warning}")

        q_out = float_to_q6_10(output)
        save_hex(q_out, os.path.join(OUTPUT_DIR2, f"{name}_out.hex"))

    print(f"\n Đã xuất {len(layer_outputs)} file Hex (Outputs) của Encoder.")

    # ---------------------------------------------------------
    # BƯỚC 6: CHẠY DECODER ĐỂ VERIFY (KHÔI PHỤC ẢNH)
    # ---------------------------------------------------------
    print("\n>>> Running DECODER Forward pass...")
    stego_quantized_sim = float_to_q6_10(stego_output).float() / Q_SCALE

    with torch.no_grad():
        recovered_secret = decoder(stego_quantized_sim)

    # ---------------------------------------------------------
    # BƯỚC 7: XUẤT ẢNH RA FILE ĐỂ XEM BẰNG MẮT THƯỜNG
    # ---------------------------------------------------------
    print(f">>> Saving Verification Images to {IMAGE_OUT_DIR}...")
    def denormalize(tensor):
        return tensor * 0.5 + 0.5

    vutils.save_image(denormalize(x_cover), os.path.join(IMAGE_OUT_DIR, "1_Original_Cover.png"))
    vutils.save_image(denormalize(x_secret), os.path.join(IMAGE_OUT_DIR, "2_Original_Secret.png"))
    vutils.save_image(denormalize(stego_quantized_sim), os.path.join(IMAGE_OUT_DIR, "3_Stego_Quantized_Q6_10.png"))
    vutils.save_image(denormalize(recovered_secret), os.path.join(IMAGE_OUT_DIR, "4_Recovered_Secret.png"))

    print("\n HOÀN TẤT TOÀN BỘ QUY TRÌNH!")
    print(f" Dữ liệu phần cứng (Weights, Biases, Outputs) tại: {OUTPUT_DIR1}")
    print(f" Ảnh kiểm chứng (Verification Images) tại     : {IMAGE_OUT_DIR}")

if __name__ == "__main__":
    main()

"""#BENCHMARK"""

import torch
import time

# ==========================================
# CẤU HÌNH
# ==========================================
MODEL_PATH = "/content/drive/MyDrive/final/final1/qat_results_q6_10/best_enc_qat_q6_10.pth"

# Tự động chọn GPU nếu có
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def measure_inference_time():
    print(">>> 1. Đang khởi tạo mô hình...")

    try:
        model = QATEncoder(base_c=32).to(DEVICE)
        model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
        model.eval()
    except Exception as e:
        print(f"⚠ Lỗi load model: {e}")
        return

    # Tạo input
    x_cover = torch.randn(1, 3, 128, 128).to(DEVICE)
    x_secret = torch.randn(1, 3, 128, 128).to(DEVICE)

    print(">>> 2. Warm-up GPU...")
    with torch.no_grad():
        for _ in range(20):
            _ = model(x_cover, x_secret)

    # 🔴 QUAN TRỌNG: đồng bộ CUDA trước khi đo
    if DEVICE.type == "cuda":
        torch.cuda.synchronize()

    print(">>> 3. Đo thời gian (100 vòng lặp)...")
    num_iterations = 100

    start_time = time.perf_counter()

    with torch.no_grad():
        for _ in range(num_iterations):
            _ = model(x_cover, x_secret)

    # 🔴 Đồng bộ lần nữa để đảm bảo GPU chạy xong
    if DEVICE.type == "cuda":
        torch.cuda.synchronize()

    end_time = time.perf_counter()

    total_time = end_time - start_time
    avg_time = total_time / num_iterations
    fps = 1.0 / avg_time

    print("\n" + "="*50)
    print("INFERENCE TIME")
    print("="*50)
    print(f" Thiết bị test        : {DEVICE.type.upper()}")
    print(f" Tổng thời gian (100x): {total_time:.4f} giây")
    print(f" Thời gian 1 ảnh      : {avg_time * 1000:.2f} ms")
    print(f" FPS                  : {fps:.2f}")
    print("="*50)

if __name__ == "__main__":
    measure_inference_time()

import torch
import torch_xla
import torch_xla.core.xla_model as xm
import time

MODEL_PATH = "/content/drive/MyDrive/final/final1/qat_results_q6_10/best_enc_qat_q6_10.pth"

def measure_inference_tpu():
    print(">>> 1. Khởi tạo TPU device...")
    device = xm.xla_device()
    print("Device:", device)

    print(">>> 2. Load model...")
    model = QATEncoder(base_c=32).to(device)
    model.load_state_dict(torch.load(MODEL_PATH, map_location="cpu"))
    model.eval()

    x_cover = torch.randn(1, 3, 128, 128).to(device)
    x_secret = torch.randn(1, 3, 128, 128).to(device)

    print(">>> 3. Warm-up TPU...")
    with torch.no_grad():
        for _ in range(10):
            _ = model(x_cover, x_secret)
            xm.mark_step()

    print(">>> 4. Đo thời gian...")
    num_iterations = 100

    start_time = time.perf_counter()

    with torch.no_grad():
        for _ in range(num_iterations):
            _ = model(x_cover, x_secret)
            xm.mark_step()

    end_time = time.perf_counter()

    total_time = end_time - start_time
    avg_time = total_time / num_iterations
    fps = 1.0 / avg_time

    print("\n" + "="*50)
    print("TPU INFERENCE TIME")
    print("="*50)
    print(f" Tổng thời gian (100x): {total_time:.4f} giây")
    print(f" Thời gian 1 ảnh      : {avg_time * 1000:.2f} ms")
    print(f" FPS                  : {fps:.2f}")
    print("="*50)


if __name__ == "__main__":
    measure_inference_tpu()
    
    
    
    
    
    
    
    
    
    
    # //////////////////////////////
    
    
    # 4) Helper cho pipeline 1.2
from torchmetrics.image.psnr import PeakSignalNoiseRatio
from torchmetrics.image.ssim import StructuralSimilarityIndexMeasure


def build_residual_vis_v12(stego, cover):
    diff = torch.abs(stego - cover)
    diff = diff / (diff.max() + 1e-8)
    return diff


class MetricBundleV12:
    def __init__(self, device):
        self.psnr = PeakSignalNoiseRatio(data_range=1.0).to(device)
        self.ssim = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)

    def calc(self, a, b):
        a01 = to_01(a)
        b01 = to_01(b)
        return float(self.psnr(a01, b01).item()), float(self.ssim(a01, b01).item())


def collect_image_paths_v12(image_dir, max_images=0):
    root = Path(image_dir)
    if not root.exists():
        raise FileNotFoundError(f"Khong tim thay image_dir: {root}")
    paths = sorted([p for p in root.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS])
    if max_images > 0:
        paths = paths[:max_images]
    if len(paths) < 12:
        raise RuntimeError("Can it nhat 12 anh de tao 10 cap eval va tap train.")
    return paths


def build_eval_pairs_v12(image_dir, img_size, num_pairs=10):
    transform = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
    ])
    paths = collect_image_paths_v12(image_dir)
    eval_paths = paths[:num_pairs]
    pairs = []
    for i in range(num_pairs):
        cover_path = eval_paths[i]
        secret_path = eval_paths[(i + 1) % num_pairs]
        cover = transform(Image.open(cover_path).convert("RGB")).unsqueeze(0)
        secret = transform(Image.open(secret_path).convert("RGB")).unsqueeze(0)
        pairs.append({"index": i, "cover_path": str(cover_path), "secret_path": str(secret_path), "cover": cover, "secret": secret})
    return pairs


def build_train_val_loaders_v12(image_dir, img_size, batch_size, num_workers, seed, train_ratio=0.9, max_images=0):
    image_paths = collect_image_paths_v12(image_dir, max_images=max_images)
    train_pool = image_paths[10:]
    dataset = ImagePathDataset(train_pool, img_size=img_size)
    train_len = max(1, int(len(dataset) * train_ratio))
    val_len = len(dataset) - train_len
    if val_len < 1:
        val_len = 1
        train_len = len(dataset) - 1
    g = torch.Generator().manual_seed(seed)
    train_ds, val_ds = random_split(dataset, [train_len, val_len], generator=g)
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=num_workers, drop_last=False, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, drop_last=False, pin_memory=True)
    return train_loader, val_loader, len(train_pool)


def save_sample_grid_v12(sample_rows, out_path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    rows = len(sample_rows)
    cols = 5
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 3.4, rows * 3.0))
    if rows == 1:
        axes = np.expand_dims(axes, axis=0)
    titles = ["Cover", "Secret", "Stego", "Residual", "Recovered"]
    for i, row in enumerate(sample_rows):
        imgs = [
            denormalize(row["cover"]).squeeze(0).permute(1, 2, 0).cpu().numpy(),
            denormalize(row["secret"]).squeeze(0).permute(1, 2, 0).cpu().numpy(),
            denormalize(row["stego"]).squeeze(0).permute(1, 2, 0).cpu().numpy(),
            denormalize(row["residual"]).squeeze(0).permute(1, 2, 0).cpu().numpy(),
            denormalize(row["recovered"]).squeeze(0).permute(1, 2, 0).cpu().numpy(),
        ]
        for j in range(cols):
            ax = axes[i, j]
            if j == 3:
                ax.imshow(imgs[j].mean(axis=2), cmap="inferno")
            else:
                ax.imshow(imgs[j])
            if i == 0:
                ax.set_title(titles[j], fontweight="bold")
            ax.axis("off")
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def evaluate_pairs_v12(encoder, decoder, eval_pairs, metrics, device, out_dir, step_name):
    encoder.eval()
    decoder.eval()
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    sample_rows = []
    with torch.no_grad():
        for item in eval_pairs:
            idx = int(item["index"])
            cover = item["cover"].to(device)
            secret = item["secret"].to(device)
            stego = encoder(cover, secret)
            recovered = decoder(stego)
            psnr_c, ssim_c = metrics.calc(stego, cover)
            psnr_s, ssim_s = metrics.calc(recovered, secret)
            rows.append({
                "index": idx,
                "cover_path": item["cover_path"],
                "secret_path": item["secret_path"],
                "psnr_cover_stego_db": psnr_c,
                "ssim_cover_stego": ssim_c,
                "psnr_secret_recovered_db": psnr_s,
                "ssim_secret_recovered": ssim_s,
                "l1_cover_stego": calc_l1(stego, cover),
                "l1_secret_recovered": calc_l1(recovered, secret),
            })
            sample_dir = out_dir / "samples" / f"pair_{idx:02d}"
            save_tensor_image(cover, sample_dir / "cover.png")
            save_tensor_image(secret, sample_dir / "secret.png")
            save_tensor_image(stego, sample_dir / "stego.png")
            save_tensor_image(recovered, sample_dir / "recovered.png")
            residual = build_residual_vis_v12(stego, cover)
            save_tensor_image(residual, sample_dir / "residual.png")
            if len(sample_rows) < 3:
                sample_rows.append({"cover": cover.cpu(), "secret": secret.cpu(), "stego": stego.cpu(), "residual": residual.cpu(), "recovered": recovered.cpu()})
    csv_path = out_dir / f"{step_name}_metrics.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    avg = {
        "avg_psnr_cover_stego_db": float(np.mean([r["psnr_cover_stego_db"] for r in rows])),
        "avg_ssim_cover_stego": float(np.mean([r["ssim_cover_stego"] for r in rows])),
        "avg_psnr_secret_recovered_db": float(np.mean([r["psnr_secret_recovered_db"] for r in rows])),
        "avg_ssim_secret_recovered": float(np.mean([r["ssim_secret_recovered"] for r in rows])),
        "avg_l1_cover_stego": float(np.mean([r["l1_cover_stego"] for r in rows])),
        "avg_l1_secret_recovered": float(np.mean([r["l1_secret_recovered"] for r in rows])),
        "metrics_csv": str(csv_path),
    }
    json_path = out_dir / f"{step_name}_summary.json"
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(avg, f, indent=2, ensure_ascii=False)
    save_sample_grid_v12(sample_rows, out_dir / f"{step_name}_sample_grid.png")
    print(f"{step_name}: PSNR_C={avg['avg_psnr_cover_stego_db']:.4f} dB | SSIM_C={avg['avg_ssim_cover_stego']:.4f} | PSNR_S={avg['avg_psnr_secret_recovered_db']:.4f} dB | SSIM_S={avg['avg_ssim_secret_recovered']:.4f}")
    return avg


def load_model_state_v12(model, ckpt_path, state_keys):
    raw = torch.load(ckpt_path, map_location="cpu")
    state = extract_state_dict(raw, state_keys)
    state = maybe_strip_prefix(state, model.state_dict().keys())
    incompatible = model.load_state_dict(state, strict=False)
    return {"missing_keys": list(incompatible.missing_keys), "unexpected_keys": list(incompatible.unexpected_keys), "loaded_keys": len(state)}


def load_qat_from_baseline_v12(qat_model, baseline_encoder):
    src = baseline_encoder.state_dict()
    dst = qat_model.state_dict()
    matched = {}
    skipped = []
    for k, v in src.items():
        if k in dst and tuple(dst[k].shape) == tuple(v.shape):
            matched[k] = v
        else:
            skipped.append(k)
    dst.update(matched)
    qat_model.load_state_dict(dst, strict=False)
    return {"matched_keys": len(matched), "total_keys": len(dst), "match_ratio": 100.0 * len(matched) / max(1, len(dst)), "skipped_keys": skipped[:20]}


def run_validation_like_stegano_fix_v12(encoder, decoder, loader, metrics, device):
    encoder.eval(); decoder.eval()
    acc = {"Cov": 0.0, "Sec": 0.0, "PSNR_C": 0.0, "SSIM_C": 0.0, "PSNR_S": 0.0, "SSIM_S": 0.0}
    l1 = nn.L1Loss(); count = 0
    with torch.no_grad():
        for cover in loader:
            cover = cover.to(device, non_blocking=True)
            secret = cover[torch.randperm(cover.size(0), device=cover.device)]
            stego = encoder(cover, secret)
            recovered = decoder(stego)
            acc["Cov"] += float(l1(stego, cover).item())
            acc["Sec"] += float(l1(recovered, secret).item())
            pc, sc = metrics.calc(stego, cover)
            ps, ss = metrics.calc(recovered, secret)
            acc["PSNR_C"] += pc; acc["SSIM_C"] += sc; acc["PSNR_S"] += ps; acc["SSIM_S"] += ss
            count += 1
    return {k: (v / max(1, count)) for k, v in acc.items()}


def fine_tune_qat_like_stegano_fix_v12(encoder_qat, decoder, train_loader, val_loader, eval_pairs, metrics, device, out_dir, epochs, lr, log_interval):
    title("STEP 2 - FINE-TUNE QAT (LIKE stegano_fix_4_5.py)")
    out_dir.mkdir(parents=True, exist_ok=True)
    l1 = nn.L1Loss(); l2 = nn.MSELoss()
    optimizer = torch.optim.Adam(list(encoder_qat.parameters()) + list(decoder.parameters()), lr=lr, betas=(0.5, 0.999))
    history = []; best_score = float("inf")
    best_enc_path = out_dir / "best_enc_qat_q6_10.pth"
    best_dec_path = out_dir / "best_dec_finetuned.pth"
    for epoch in range(1, epochs + 1):
        encoder_qat.train(); decoder.train()
        running = {"Loss_G": 0.0, "Cov": 0.0, "Sec": 0.0}
        for step, cover in enumerate(train_loader, start=1):
            cover = cover.to(device, non_blocking=True)
            secret = cover[torch.randperm(cover.size(0), device=cover.device)]
            optimizer.zero_grad(set_to_none=True)
            stego = encoder_qat(cover, secret)
            recovered = decoder(stego)
            loss_cov = 1.0 * l1(stego, cover) + 0.5 * l2(stego, cover)
            loss_sec = 1.0 * l1(recovered, secret) + 0.5 * l2(recovered, secret)
            loss_g = loss_cov + loss_sec
            loss_g.backward()
            torch.nn.utils.clip_grad_norm_(list(encoder_qat.parameters()) + list(decoder.parameters()), 1.0)
            optimizer.step()
            running["Loss_G"] += float(loss_g.item()); running["Cov"] += float(loss_cov.item()); running["Sec"] += float(loss_sec.item())
            if log_interval > 0 and step % log_interval == 0:
                print(f"[FT] Ep{epoch} Step{step}/{len(train_loader)} | Loss_G={loss_g.item():.6f} | Cov={loss_cov.item():.6f} | Sec={loss_sec.item():.6f}")
        den = max(1, len(train_loader))
        val_res = run_validation_like_stegano_fix_v12(encoder_qat, decoder, val_loader, metrics, device=device)
        score = val_res["Cov"] + val_res["Sec"]
        history.append({"epoch": float(epoch), "train_loss_g": running["Loss_G"] / den, "train_cov": running["Cov"] / den, "train_sec": running["Sec"] / den, "val_cov": val_res["Cov"], "val_sec": val_res["Sec"], "val_psnr_c": val_res["PSNR_C"], "val_ssim_c": val_res["SSIM_C"], "val_psnr_s": val_res["PSNR_S"], "val_ssim_s": val_res["SSIM_S"]})
        print(f"[VAL] Epoch {epoch}/{epochs} | Score={score:.6f} | COVER PSNR={val_res['PSNR_C']:.4f} SSIM={val_res['SSIM_C']:.4f} | SECRET PSNR={val_res['PSNR_S']:.4f} SSIM={val_res['SSIM_S']:.4f}")
        evaluate_pairs_v12(encoder_qat, decoder, eval_pairs, metrics, device, out_dir / f"epoch_{epoch:02d}", f"epoch_{epoch:02d}")
        if score < best_score:
            best_score = score
            torch.save(encoder_qat.state_dict(), best_enc_path)
            torch.save(decoder.state_dict(), best_dec_path)
    hist_csv = out_dir / "finetune_history.csv"
    with hist_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(history[0].keys())); writer.writeheader(); writer.writerows(history)
    hist_json = out_dir / "finetune_history.json"
    with hist_json.open("w", encoding="utf-8") as f:
        json.dump(history, f, indent=2, ensure_ascii=False)
    encoder_qat.load_state_dict(torch.load(best_enc_path, map_location=device), strict=True)
    decoder.load_state_dict(torch.load(best_dec_path, map_location=device), strict=True)
    return {"best_score": best_score, "best_enc_path": str(best_enc_path), "best_dec_path": str(best_dec_path), "history_csv": str(hist_csv), "history_json": str(hist_json)}


def save_weight_and_bn_info_v12(model, model_name, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    state_path = out_dir / f"{model_name}_state_dict.pth"
    torch.save(model.state_dict(), state_path)
    weight_rows = []; bn_rows = []
    for name, tensor in model.state_dict().items():
        t = tensor.detach().float().cpu()
        weight_rows.append({"name": name, "shape": str(list(t.shape)), "min": float(t.min().item()) if t.numel() > 0 else 0.0, "max": float(t.max().item()) if t.numel() > 0 else 0.0, "mean": float(t.mean().item()) if t.numel() > 0 else 0.0, "std": float(t.std().item()) if t.numel() > 1 else 0.0})
    for name, module in model.named_modules():
        if isinstance(module, nn.BatchNorm2d):
            bn_rows.append({"name": name, "num_features": module.num_features, "eps": module.eps, "momentum": module.momentum if module.momentum is not None else -1.0, "weight_mean": float(module.weight.detach().float().mean().item()), "bias_mean": float(module.bias.detach().float().mean().item()), "running_mean_mean": float(module.running_mean.detach().float().mean().item()), "running_var_mean": float(module.running_var.detach().float().mean().item())})
    weights_csv = out_dir / f"{model_name}_weights_summary.csv"
    with weights_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(weight_rows[0].keys())); writer.writeheader(); writer.writerows(weight_rows)
    bn_csv = out_dir / f"{model_name}_batchnorm_summary.csv"
    if bn_rows:
        with bn_csv.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(bn_rows[0].keys())); writer.writeheader(); writer.writerows(bn_rows)
    return {"state_dict": str(state_path), "weights_csv": str(weights_csv), "batchnorm_csv": str(bn_csv)}


def run_pipeline_v12(cfg):
    out_dir = Path(cfg.output_dir); out_dir.mkdir(parents=True, exist_ok=True)
    device = torch.device(cfg.device); torch.manual_seed(cfg.seed)
    title("QAT FINAL PIPELINE 1.2")
    print(f"Device: {device}"); print(f"Output dir: {out_dir}"); print(f"Image dir: {cfg.image_dir}")
    metrics = MetricBundleV12(device)
    eval_pairs = build_eval_pairs_v12(cfg.image_dir, cfg.img_size, num_pairs=cfg.eval_count)
    enc_base = Encoder(base_c=cfg.base_c).to(device); dec_base = Decoder(base_c=cfg.base_c).to(device)
    title("LOAD BASELINE MODELS")
    enc_info = load_model_state_v12(enc_base, cfg.baseline_enc_ckpt, ("enc", "encoder", "state_dict", "model"))
    dec_info = load_model_state_v12(dec_base, cfg.baseline_dec_ckpt, ("dec", "decoder", "state_dict", "model"))
    print(f"Encoder loaded keys: {enc_info['loaded_keys']}"); print(f"Decoder loaded keys: {dec_info['loaded_keys']}")
    print(f"Encoder missing: {len(enc_info['missing_keys'])} | unexpected: {len(enc_info['unexpected_keys'])}")
    print(f"Decoder missing: {len(dec_info['missing_keys'])} | unexpected: {len(dec_info['unexpected_keys'])}")
    step1_dir = out_dir / "step1_baseline_10_images"
    title("STEP 1 - BASELINE ON FIRST 10 IMAGE PAIRS")
    step1_summary = evaluate_pairs_v12(enc_base, dec_base, eval_pairs, metrics, device, step1_dir, "step1_baseline")
    title("STEP 2 - FINE-TUNE QAT MODEL WITH Q6.10")
    enc_qat = QATEncoder(base_c=cfg.base_c).to(device); dec_ft = Decoder(base_c=cfg.base_c).to(device)
    load_qat_info = load_qat_from_baseline_v12(enc_qat, enc_base)
    dec_ft.load_state_dict(dec_base.state_dict(), strict=True)
    print(f"QAT init from baseline: {load_qat_info['matched_keys']}/{load_qat_info['total_keys']} ({load_qat_info['match_ratio']:.2f}%)")
    pre_ft_dir = out_dir / "step2_qat_pre_finetune"
    pre_ft_summary = evaluate_pairs_v12(enc_qat, dec_ft, eval_pairs, metrics, device, pre_ft_dir, "step2_pre_finetune")
    train_loader, val_loader, train_pool = build_train_val_loaders_v12(cfg.image_dir, img_size=cfg.img_size, batch_size=cfg.batch_size, num_workers=cfg.num_workers, seed=cfg.seed, train_ratio=cfg.train_ratio, max_images=cfg.max_train_images)
    print(f"Train pool images: {train_pool} | Train batches: {len(train_loader)} | Val batches: {len(val_loader)}")
    ft_info = fine_tune_qat_like_stegano_fix_v12(enc_qat, dec_ft, train_loader=train_loader, val_loader=val_loader, eval_pairs=eval_pairs, metrics=metrics, device=device, out_dir=out_dir / "step2_qat_finetune", epochs=cfg.ft_epochs, lr=cfg.ft_lr, log_interval=cfg.log_interval)
    post_ft_dir = out_dir / "step2_qat_post_finetune"
    post_ft_summary = evaluate_pairs_v12(enc_qat, dec_ft, eval_pairs, metrics, device, post_ft_dir, "step2_post_finetune")
    title("STEP 3 - SAVE ALL WEIGHTS AND BATCHNORM INFO")
    step3_dir = out_dir / "step3_weights_and_bn"
    enc_saved = save_weight_and_bn_info_v12(enc_qat.cpu().eval(), "encoder_qat", step3_dir)
    dec_saved = save_weight_and_bn_info_v12(dec_ft.cpu().eval(), "decoder_finetuned", step3_dir)
    enc_qat = enc_qat.to(device); dec_ft = dec_ft.to(device)
    step3_summary = evaluate_pairs_v12(enc_qat, dec_ft, eval_pairs, metrics, device, step3_dir / "eval", "step3_eval")
    title("STEP 4 - FUSE WEIGHT + BN AND VERIFY SMALL CHANGE")
    step4_dir = out_dir / "step4_fuse_verify"
    enc_fused = copy.deepcopy(enc_qat).to(device).eval(); fuse_model_qat(enc_fused); enc_fused = enc_fused.to(device)
    step4_summary = evaluate_pairs_v12(enc_fused, dec_ft, eval_pairs, metrics, device, step4_dir, "step4_fused")
    with torch.no_grad():
        cover0 = eval_pairs[0]["cover"].to(device); secret0 = eval_pairs[0]["secret"].to(device)
        r2 = enc_qat(cover0, secret0); r3 = enc_fused(cover0, secret0); rec2 = dec_ft(r2); rec3 = dec_ft(r3)
    fuse_verify = {"allclose_stego_atol_1e6": bool(torch.allclose(r2, r3, atol=1e-6)), "allclose_stego_atol_1lsb": bool(torch.allclose(r2, r3, atol=1.0 / Q_SCALE)), "max_abs_diff_stego": float(torch.max(torch.abs(r2 - r3)).item()), "psnr_stego_r2_r3_db": calc_psnr_scalar(to_01(r2), to_01(r3)), "psnr_recover_r2_r3_db": calc_psnr_scalar(to_01(rec2), to_01(rec3))}
    with (step4_dir / "fuse_verify.json").open("w", encoding="utf-8") as f:
        json.dump(fuse_verify, f, indent=2, ensure_ascii=False)
    print(json.dumps(fuse_verify, indent=2))
    title("STEP 5 - EXPORT .MEM FOR POINTWISE AND DEPTHWISE")
    step5_dir = out_dir / "step5_mem_export"
    enc_fused_cpu = copy.deepcopy(enc_fused).cpu().eval()
    dw_path, pw_path, map_info = export_mem_files_with_map(enc_fused_cpu, step5_dir, insert_deadbeef_after_head=cfg.insert_deadbeef_after_head)
    print(f"Depthwise mem: {dw_path}"); print(f"Pointwise mem: {pw_path}")
    print_memory_map(map_info)
    save_memory_map_csv(map_info, step5_dir / "memory_map.csv")
    step5_summary = evaluate_pairs_v12(enc_fused, dec_ft, eval_pairs, metrics, device, step5_dir / "eval", "step5_eval")
    title("STEP 6 - GOLDEN MODEL (INPUT/ACTIVATION/OUTPUT HEX)")
    step6_dir = out_dir / "step6_golden_model"; step6_dir.mkdir(parents=True, exist_ok=True)
    pair0 = eval_pairs[0]; x_cover = pair0["cover"]; x_secret = pair0["secret"]
    print(f"Golden sample cover : {pair0['cover_path']}"); print(f"Golden sample secret: {pair0['secret_path']}")
    save_hex(float_to_q6_10(x_cover), step6_dir / "000_input_cover.hex"); save_hex(float_to_q6_10(x_secret), step6_dir / "000_input_secret.hex")
    x_cover_sim = float_to_q6_10(x_cover).float() / Q_SCALE; x_secret_sim = float_to_q6_10(x_secret).float() / Q_SCALE
    layer_outputs = {}; hooks = register_hooks(enc_fused_cpu, layer_outputs)
    with torch.no_grad():
        stego_out = enc_fused_cpu(x_cover_sim, x_secret_sim)
    for h in hooks: h.remove()
    save_hex(float_to_q6_10(stego_out), step6_dir / "999_stego_output.hex")
    activation_rows = []
    for name, output in layer_outputs.items():
        save_hex(float_to_q6_10(output), step6_dir / "activations" / f"{name}_out.hex")
        f_min = float(output.min()); f_max = float(output.max())
        activation_rows.append({"layer": name, "shape": str(list(output.shape)), "min": f_min, "max": f_max, "overflow_q6_10": bool(f_min < -32.0 or f_max >= 32.0)})
    with (step6_dir / "activation_summary.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(activation_rows[0].keys())); writer.writeheader(); writer.writerows(activation_rows)
    with torch.no_grad(): recovered_out = dec_ft.cpu().eval()(stego_out)
    save_tensor_image(stego_out, step6_dir / "stego_output.png"); save_tensor_image(recovered_out, step6_dir / "recovered_output.png"); save_tensor_image(build_residual_vis_v12(stego_out, x_cover), step6_dir / "residual_output.png")
    step6_summary = evaluate_pairs_v12(enc_fused, dec_ft.to(device), eval_pairs, metrics, device, step6_dir / "eval", "step6_eval")
    summary = {"step1": step1_summary, "step2_pre_finetune": pre_ft_summary, "step2_finetune_info": ft_info, "step2_post_finetune": post_ft_summary, "step3": {"saved_encoder": enc_saved, "saved_decoder": dec_saved, "eval": step3_summary}, "step4": {"eval": step4_summary, "verify": fuse_verify}, "step5": {"depthwise_mem": str(dw_path), "pointwise_mem": str(pw_path), "map_entries": len(map_info), "eval": step5_summary}, "step6": {"activation_count": len(activation_rows), "eval": step6_summary}}
    with (out_dir / "summary_v1_2.json").open("w", encoding="utf-8") as f: json.dump(summary, f, indent=2, ensure_ascii=False)
    print("\nPipeline 1.2 completed."); print(f"Summary: {out_dir / 'summary_v1_2.json'}")
