# -*- coding: utf-8 -*-
"""qat_final_cells_outputs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sXu-v4OSJW4QNZk0qXibuUbHEa2XqLz
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("xhlulu/140k-real-and-fake-faces")

print("Path to dataset files:", path)

from google.colab import drive
import os

print("Đang kết nối Google Drive...")
drive.mount('/content/drive')

!pip install torchmetrics

import os, copy, csv, time, math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import torchvision.utils as vutils
from PIL import Image
import matplotlib.pyplot as plt
from torchmetrics.image.psnr import PeakSignalNoiseRatio
from torchmetrics.image.ssim import StructuralSimilarityIndexMeasure

# ── 0.2  Cấu hình đường dẫn ─────────────────────────────────────────────────
# ==========================================
# CẬP NHẬT LẠI LỚP CONFIG TRONG CELL 0
# ==========================================
class Config:
    # Thư mục ảnh lấy từ file stegano_fix_4_5.py
    TRAIN_REAL_DIR  = "/kaggle/input/140k-real-and-fake-faces/real_vs_fake/real-vs-fake/train/real"
    VAL_REAL_DIR    = "/kaggle/input/140k-real-and-fake-faces/real_vs_fake/real-vs-fake/valid/real"

    # Thư mục lưu kết quả (Dùng đường dẫn Google Drive từ file gốc)
    SAVE_DIR        = "/content/drive/MyDrive/final/stegano_fix_4.4/golden_v2"
    SAVE_DIR1        = "/content/drive/MyDrive/final/stegano_fix_4.4"
    # Đường dẫn checkpoint Baseline (Float32) đã train sẵn
    # Theo file gốc, tên file lưu là best_enc.pth và best_dec.pth
    BASELINE_ENC_PTH = os.path.join(SAVE_DIR1, "best_enc.pth")
    BASELINE_DEC_PTH = os.path.join(SAVE_DIR1, "best_dec.pth")

    # Tham số model
    IMG_SIZE        = 128
    BATCH_SIZE      = 32
    BASE_CHANNEL    = 16 # base_c từ file gốc

    # Tham số QAT Fine-tune
    QAT_EPOCHS      = 5  # Fine-tune ngắn theo yêu cầu
    QAT_LR          = 1e-5 # LR thấp để tinh chỉnh

    # Loss weights (Đúng theo stegano_fix_4_5.py)
    LAMBDA_COVER_L1  = 1.0
    LAMBDA_COVER_L2  = 0.5
    LAMBDA_SECRET_L1 = 1.0
    LAMBDA_SECRET_L2 = 0.5

    DEVICE          = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    SEED            = 42

# Khởi tạo
os.makedirs(Config.SAVE_DIR, exist_ok=True)
torch.manual_seed(Config.SEED)
print(f"[Cell 0] Device: {Config.DEVICE}")
print(f"[Cell 0] Save Directory: {Config.SAVE_DIR}")

Q_FRAC   = 10
Q_SCALE  = float(2 ** Q_FRAC)   # 1024.0
INT16_MIN, INT16_MAX = -32768, 32767

# ── 0.4  FakeQuantize (STE) ─────────────────────────────────────────────────
class FakeQuantizeQ6_10(torch.autograd.Function):
    """Q6.10: scale=1024, range [-32.0, +31.999], STE backward."""
    @staticmethod
    def forward(ctx, x):
        return torch.round(x * Q_SCALE).clamp(INT16_MIN, INT16_MAX) / Q_SCALE
    @staticmethod
    def backward(ctx, grad):
        return grad

def qat_quant(x):
    return FakeQuantizeQ6_10.apply(x)

class QuantIdentity(nn.Module):
    def forward(self, x):
        return qat_quant(x)

# ── 0.5  Kiến trúc chung: SeparableConv2d ───────────────────────────────────
class SeparableConv2d(nn.Module):
    def __init__(self, in_c, out_c, kernel_size=3, stride=1, padding=1):
        super().__init__()
        self.depthwise = nn.Conv2d(in_c, in_c, kernel_size, stride, padding,
                                   groups=in_c, bias=False)
        self.pointwise = nn.Conv2d(in_c, out_c, kernel_size=1, bias=False)

    def forward(self, x):
        return self.pointwise(self.depthwise(x))

# ── 0.6  Kiến trúc QAT: QATSeparableConv2d ──────────────────────────────────
class QATSeparableConv2d(nn.Module):
    """Depthwise+Pointwise với FakeQuantize trọng số và kết quả trung gian.

    Sau khi fuse BN (Cell 3), thuộc tính `bn_fused=True` được set.
    Lúc đó:
      - Pointwise weight đã hấp thụ BN → KHÔNG quantize lại (sẽ sai)
      - Pointwise bias đã hấp thụ BN → truyền thẳng vào F.conv2d
    """
    def __init__(self, in_c, out_c, kernel_size=3, stride=1, padding=1):
        super().__init__()
        self.depthwise = nn.Conv2d(in_c, in_c, kernel_size, stride, padding,
                                   groups=in_c, bias=False)
        self.pointwise = nn.Conv2d(in_c, out_c, kernel_size=1, bias=False)
        self.bn_fused  = False   # set True bởi fuse_model_qat

    def forward(self, x):
        # ── Depthwise: luôn quantize weight (không bao giờ fuse DW+BN) ──────
        w_dw = qat_quant(self.depthwise.weight)
        x = F.conv2d(x, w_dw, None,
                     self.depthwise.stride, self.depthwise.padding,
                     self.depthwise.dilation, self.depthwise.groups)
        x = qat_quant(x)    # quantize activation trung gian

        # ── Pointwise: hành vi khác nhau tuỳ trạng thái fuse ────────────────
        if self.bn_fused:
            # Weight và bias đã hấp thụ BN → dùng trực tiếp, KHÔNG quantize
            x = F.conv2d(x, self.pointwise.weight, self.pointwise.bias,
                         self.pointwise.stride, self.pointwise.padding)
        else:
            # Chế độ QAT bình thường → quantize weight trước khi nhân
            w_pw = qat_quant(self.pointwise.weight)
            b_pw = self.pointwise.bias  # None trước fuse
            x = F.conv2d(x, w_pw, b_pw,
                         self.pointwise.stride, self.pointwise.padding)
        return x

# ── 0.7  Baseline Encoder (Float32) ─────────────────────────────────────────
class Encoder(nn.Module):
    """U-Net Encoder dùng SeparableConv2d thuần Float32."""
    def __init__(self, base_c=16):
        super().__init__()

        def conv_block(in_c, out_c, stride=1):
            return nn.Sequential(
                SeparableConv2d(in_c, out_c, stride=stride),
                nn.BatchNorm2d(out_c),
                nn.LeakyReLU(0.1, inplace=True))

        def conv_block_no_act(in_c, out_c):
            return nn.Sequential(SeparableConv2d(in_c, out_c))

        self.head       = conv_block(6,            base_c)           # 128×128
        self.down1      = conv_block(base_c,       base_c*2, stride=2)  # 64×64
        self.down2      = conv_block(base_c*2,     base_c*4, stride=2)  # 32×32
        self.down3      = conv_block(base_c*4,     base_c*8, stride=2)  # 16×16
        self.bottleneck = conv_block(base_c*8,     base_c*8, stride=2)  #  8×8
        self.upsample   = nn.Upsample(scale_factor=2, mode='nearest')
        self.up1        = conv_block(base_c*8*2,   base_c*4)
        self.up2        = conv_block(base_c*4*2,   base_c*2)
        self.up3        = conv_block(base_c*2*2,   base_c)
        self.up4        = conv_block(base_c*2,     base_c)
        self.tail       = conv_block_no_act(base_c, 3)

    def forward(self, x_cover, x_secret):
        x  = torch.cat([x_cover, x_secret], dim=1)
        h  = self.head(x)
        d1 = self.down1(h)
        d2 = self.down2(d1)
        d3 = self.down3(d2)
        b  = self.bottleneck(d3)
        u1 = self.up1(torch.cat([self.upsample(b),  d3], dim=1))
        u2 = self.up2(torch.cat([self.upsample(u1), d2], dim=1))
        u3 = self.up3(torch.cat([self.upsample(u2), d1], dim=1))
        u4 = self.up4(torch.cat([self.upsample(u3), h],  dim=1))
        return torch.clamp(x_cover + self.tail(u4), -1, 1)

# ── 0.8  Baseline Decoder (Float32) ─────────────────────────────────────────
class Decoder(nn.Module):
    """U-Net Decoder dùng Full Conv Float32."""
    def __init__(self, base_c=16):
        super().__init__()

        def conv_block(in_c, out_c, stride=1):
            return nn.Sequential(
                nn.Conv2d(in_c, out_c, 3, stride, 1, bias=True),
                nn.BatchNorm2d(out_c),
                nn.LeakyReLU(0.1, inplace=True))

        self.head       = conv_block(3,           base_c)
        self.down1      = conv_block(base_c,      base_c*2,  stride=2)
        self.down2      = conv_block(base_c*2,    base_c*4,  stride=2)
        self.down3      = conv_block(base_c*4,    base_c*8,  stride=2)
        self.down4      = conv_block(base_c*8,    base_c*16, stride=2)
        self.bottleneck = conv_block(base_c*16,   base_c*16, stride=2)
        self.upsample   = nn.Upsample(scale_factor=2, mode='bilinear',
                                       align_corners=True)
        self.up1        = conv_block(base_c*16*2, base_c*8)
        self.up2        = conv_block(base_c*8*2,  base_c*4)
        self.up3        = conv_block(base_c*4*2,  base_c*2)
        self.up4        = conv_block(base_c*2*2,  base_c)
        self.up5        = conv_block(base_c*2,    base_c)
        self.tail       = nn.Sequential(
            nn.Conv2d(base_c, 3, 3, padding=1), nn.Tanh())

    def forward(self, x):
        c1 = self.head(x)
        c2 = self.down1(c1)
        c3 = self.down2(c2)
        c4 = self.down3(c3)
        c5 = self.down4(c4)
        b  = self.bottleneck(c5)
        u1 = self.up1(torch.cat([self.upsample(b),  c5], dim=1))
        u2 = self.up2(torch.cat([self.upsample(u1), c4], dim=1))
        u3 = self.up3(torch.cat([self.upsample(u2), c3], dim=1))
        u4 = self.up4(torch.cat([self.upsample(u3), c2], dim=1))
        u5 = self.up5(torch.cat([self.upsample(u4), c1], dim=1))
        return self.tail(u5)

# ── 0.9  QAT Encoder ────────────────────────────────────────────────────────
class QATEncoder(nn.Module):
    """Encoder dùng QATSeparableConv2d + FakeQuantize activations.

    Tên attribute và key state_dict cố tình giữ GIỐNG Baseline Encoder:
      head / down1 / down2 / down3 / bottleneck / up1..up4 / tail
    → load_qat_from_baseline sẽ match được 100% key.
    Điểm khác: các block dùng QATSeparableConv2d thay vì SeparableConv2d,
    thêm ReLU + QuantIdentity (BN key vẫn giữ nguyên).
    """
    def __init__(self, base_c=16):
        super().__init__()

        def qat_block(in_c, out_c, stride=1):
            return nn.Sequential(
                QATSeparableConv2d(in_c, out_c, stride=stride),
                nn.BatchNorm2d(out_c),
                nn.ReLU(inplace=True),
                QuantIdentity())          # quantize activation sau ReLU

        def qat_block_no_act(in_c, out_c):
            """Giống conv_block_no_relu của Baseline: chỉ có SeparableConv.
            Key: tail.0.depthwise.weight, tail.0.pointwise.weight
            """
            return nn.Sequential(QATSeparableConv2d(in_c, out_c))

        # Tên PHẢI khớp với Baseline Encoder để copy weight
        self.head       = qat_block(6,          base_c)
        self.down1      = qat_block(base_c,     base_c*2, stride=2)
        self.down2      = qat_block(base_c*2,   base_c*4, stride=2)
        self.down3      = qat_block(base_c*4,   base_c*8, stride=2)
        self.bottleneck = qat_block(base_c*8,   base_c*8, stride=2)
        self.upsample   = nn.Upsample(scale_factor=2, mode='nearest')
        self.up1        = qat_block(base_c*8*2, base_c*4)
        self.up2        = qat_block(base_c*4*2, base_c*2)
        self.up3        = qat_block(base_c*2*2, base_c)
        self.up4        = qat_block(base_c*2,   base_c)
        # tail giống Baseline: Sequential(QATSeparableConv2d(base_c, 3))
        # key: tail.0.depthwise.weight / tail.0.pointwise.weight
        self.tail       = qat_block_no_act(base_c, 3)

    def forward(self, x_cover, x_secret):
        # Quantize input (mô phỏng pixel 16-bit vào FPGA)
        x_cover  = qat_quant(x_cover)
        x_secret = qat_quant(x_secret)
        x  = torch.cat([x_cover, x_secret], dim=1)
        h  = self.head(x)
        d1 = self.down1(h)
        d2 = self.down2(d1)
        d3 = self.down3(d2)
        b  = self.bottleneck(d3)
        u1 = self.up1(torch.cat([self.upsample(b),  d3], dim=1))
        u2 = self.up2(torch.cat([self.upsample(u1), d2], dim=1))
        u3 = self.up3(torch.cat([self.upsample(u2), d1], dim=1))
        u4 = self.up4(torch.cat([self.upsample(u3), h],  dim=1))

        # Quantize weight lớp tail trước khi chạy (forward thủ công)
        sep = self.tail[0]                              # QATSeparableConv2d
        w_dw = qat_quant(sep.depthwise.weight)
        feat = F.conv2d(u4, w_dw, None,
                        sep.depthwise.stride, sep.depthwise.padding,
                        sep.depthwise.dilation, sep.depthwise.groups)
        feat = qat_quant(feat)
        w_pw = qat_quant(sep.pointwise.weight)
        out  = F.conv2d(feat, w_pw, None,
                        sep.pointwise.stride, sep.pointwise.padding)

        # Quantize output cuối (sau Tanh + residual)
        out = qat_quant(torch.tanh(out))
        return torch.clamp(x_cover + out, -1, 1)

# ── 0.10 Dataset & DataLoader ────────────────────────────────────────────────
class RealImageDataset(Dataset):
    def __init__(self, directory, img_size=128):
        try:
            self.paths = [os.path.join(directory, f)
                          for f in sorted(os.listdir(directory))
                          if f.lower().endswith(('png','jpg','jpeg'))]
        except Exception:
            self.paths = []
        self.transform = transforms.Compose([
            transforms.Resize((img_size, img_size)),
            transforms.ToTensor(),
            transforms.Normalize([0.5]*3, [0.5]*3)])

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, i):
        try:
            return self.transform(Image.open(self.paths[i]).convert("RGB"))
        except Exception:
            return torch.zeros(3, 128, 128)

def get_loaders(cfg):
    train_ds = RealImageDataset(cfg.TRAIN_REAL_DIR, cfg.IMG_SIZE)
    val_ds   = RealImageDataset(cfg.VAL_REAL_DIR,   cfg.IMG_SIZE)
    dl_train = DataLoader(train_ds, batch_size=cfg.BATCH_SIZE,
                          shuffle=True,  num_workers=2, drop_last=True)
    dl_val   = DataLoader(val_ds,   batch_size=cfg.BATCH_SIZE,
                          shuffle=False, num_workers=2, drop_last=True)
    return dl_train, dl_val

# ── 0.11 Metric helpers ──────────────────────────────────────────────────────
def build_metrics(device):
    psnr_fn = PeakSignalNoiseRatio(data_range=1.0).to(device)
    ssim_fn = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)
    return psnr_fn, ssim_fn

def calc_metrics(i1, i2, psnr_fn, ssim_fn):
    i1 = ((i1 + 1) / 2).clamp(0, 1)
    i2 = ((i2 + 1) / 2).clamp(0, 1)
    return psnr_fn(i1, i2).item(), ssim_fn(i1, i2).item()

def denorm_np(t):
    """Tensor [B,C,H,W] → numpy [B,H,W,C] in [0,1]."""
    return ((t + 1) / 2).clamp(0, 1).cpu().permute(0, 2, 3, 1).numpy()

# ── 0.12 HEX / Q6.10 helpers ────────────────────────────────────────────────
def float_to_q6_10(x: torch.Tensor) -> torch.Tensor:
    """Float tensor (bất kỳ device) → int16 tensor trên CPU (Q6.10)."""
    return (torch.round(x.detach().float().cpu() * Q_SCALE)
              .clamp(INT16_MIN, INT16_MAX)
              .to(torch.int16))

def save_hex(tensor_int16: torch.Tensor, filepath: str):
    """Lưu int16 tensor ra file hex 4 ký tự / dòng (two's complement).
    Tự động chuyển về CPU nếu tensor đang trên GPU.
    """
    os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
    arr = tensor_int16.detach().cpu().contiguous().view(-1).numpy().astype(np.int32)
    with open(filepath, "w") as f:
        for v in arr:
            f.write(f"{v & 0xFFFF:04x}\n")

def export_io_hex(cover, secret, stego, recover, out_dir, prefix=""):
    """Xuất 4 file HEX cho 1 cặp ảnh mẫu."""
    os.makedirs(out_dir, exist_ok=True)
    p = lambda name: os.path.join(out_dir, f"{prefix}{name}.hex")
    save_hex(float_to_q6_10(cover.cpu()),   p("input_cover"))
    save_hex(float_to_q6_10(secret.cpu()),  p("input_secret"))
    save_hex(float_to_q6_10(stego.cpu()),   p("output_stego"))
    save_hex(float_to_q6_10(recover.cpu()), p("output_recover"))
    print(f"  [HEX] Xuất 4 file hex vào: {out_dir}")

# ── 0.13 Visualization helper ────────────────────────────────────────────────
def show_4_images(cover, secret, stego, recover, title="", save_path=None):
    """Hiển thị 4 ảnh Cover / Secret / Stego / Recover cho batch[0]."""
    imgs = [denorm_np(t)[0] for t in [cover, secret, stego, recover]]
    lbls = ["Cover", "Secret", "Stego", "Recover"]
    fig, axes = plt.subplots(1, 4, figsize=(14, 4))
    fig.suptitle(title, fontsize=13, fontweight='bold')
    for ax, img, lbl in zip(axes, imgs, lbls):
        ax.imshow(img); ax.set_title(lbl); ax.axis('off')
    plt.tight_layout()
    if save_path:
        os.makedirs(os.path.dirname(os.path.abspath(save_path)), exist_ok=True)
        plt.savefig(save_path, dpi=100)
    plt.show()
    print(f"  [VIS] {title}")

# ── 0.14 Eval loop (PSNR / SSIM over full dataset) ──────────────────────────
def eval_dataset(encoder, decoder, loader, psnr_fn, ssim_fn, device,
                 label="Model"):
    """Chạy qua toàn bộ loader, trả về dict chỉ số trung bình."""
    encoder.eval(); decoder.eval()
    acc = {"PSNR_C": 0., "SSIM_C": 0., "PSNR_S": 0., "SSIM_S": 0.}
    n = 0
    with torch.no_grad():
        for cover in loader:
            cover  = cover.to(device)
            secret = cover[torch.randperm(cover.size(0))].to(device)
            stego  = encoder(cover, secret)
            rev    = decoder(stego)
            pc, sc = calc_metrics(stego, cover,  psnr_fn, ssim_fn)
            ps, ss = calc_metrics(rev,   secret, psnr_fn, ssim_fn)
            acc["PSNR_C"] += pc; acc["SSIM_C"] += sc
            acc["PSNR_S"] += ps; acc["SSIM_S"] += ss
            n += 1
    res = {k: v / max(n, 1) for k, v in acc.items()}
    print(f"\n[{label}] ── Đánh giá toàn dataset ({n} batches) ──")
    print(f"  Stego  : PSNR={res['PSNR_C']:.2f} dB | SSIM={res['SSIM_C']:.4f}")
    print(f"  Recover: PSNR={res['PSNR_S']:.2f} dB | SSIM={res['SSIM_S']:.4f}")
    return res

print("[Cell 0] Hoàn tất – Kiến trúc và utils đã sẵn sàng.")

# %%===========================================================================
# CELL 1 – ĐÁNH GIÁ BASELINE MODEL (Float32)
# =============================================================================
"""
Yêu cầu:
  - Load trọng số pre-trained Baseline.
  - Lấy 1 cặp ảnh mẫu, hiển thị Cover/Secret/Stego/Recover.
  - Xuất HEX 16-bit (Q6.10) input & output của cặp mẫu đó.
  - Lưu weight + BN ra .pth và .hex.
  - Đo PSNR/SSIM trên toàn dataset.
"""

# ── 1.0  Bootstrap (Cell 1 có thể chạy độc lập) ─────────────────────────────
cfg          = Config()
device       = cfg.DEVICE
torch.manual_seed(cfg.SEED)
os.makedirs(cfg.SAVE_DIR, exist_ok=True)
psnr_fn, ssim_fn = build_metrics(device)
dl_train, dl_val  = get_loaders(cfg)
print(f"[Cell 1] Device={device} | Val batches={len(dl_val)}")

# ── 1.1  Khởi tạo model ─────────────────────────────────────────────────────
enc_base = Encoder(base_c=cfg.BASE_CHANNEL).to(device)
dec_base = Decoder(base_c=cfg.BASE_CHANNEL).to(device)

# ── 1.2  Load pre-trained weights ───────────────────────────────────────────
def load_baseline_weights(enc, dec, enc_path, dec_path, device):
    for model, path, name in [(enc, enc_path, "Encoder"),
                               (dec, dec_path, "Decoder")]:
        if os.path.exists(path):
            raw = torch.load(path, map_location=device)
            # Hỗ trợ cả checkpoint (dict có key 'enc'/'dec') lẫn state_dict thuần
            if isinstance(raw, dict):
                for key in ('enc', 'encoder', 'dec', 'decoder', 'state_dict'):
                    if key in raw:
                        raw = raw[key]; break
            model.load_state_dict(raw, strict=False)
            print(f"  [Load] {name} ← {path}")
        else:
            print(f"  [WARN] Không tìm thấy {path} – dùng random weights để demo.")

load_baseline_weights(enc_base, dec_base,
                      cfg.BASELINE_ENC_PTH, cfg.BASELINE_DEC_PTH, device)
enc_base.eval(); dec_base.eval()

# ── 1.3  Lấy 1 cặp ảnh mẫu (cố định, dùng lại ở Cell 2, 3, 5) ──────────────
_batch = next(iter(dl_val)).to(device)
SAMPLE_COVER  = _batch[:1].clone()                              # 1 ảnh
SAMPLE_SECRET = _batch[1:2].clone() if _batch.size(0) > 1 \
                else _batch[:1].clone()

with torch.no_grad():
    SAMPLE_STEGO_BASE   = enc_base(SAMPLE_COVER, SAMPLE_SECRET)
    SAMPLE_RECOVER_BASE = dec_base(SAMPLE_STEGO_BASE)

# ── 1.4  Hiển thị 4 ảnh ─────────────────────────────────────────────────────
show_4_images(
    SAMPLE_COVER, SAMPLE_SECRET,
    SAMPLE_STEGO_BASE, SAMPLE_RECOVER_BASE,
    title="Cell 1 – Baseline Float32",
    save_path=os.path.join(cfg.SAVE_DIR, "cell1_baseline_sample.png"))

# ── 1.5  Xuất HEX input/output ──────────────────────────────────────────────
cell1_hex_dir = os.path.join(cfg.SAVE_DIR, "cell1_hex")
export_io_hex(SAMPLE_COVER, SAMPLE_SECRET,
              SAMPLE_STEGO_BASE, SAMPLE_RECOVER_BASE,
              cell1_hex_dir, prefix="baseline_")

# ── 1.6  Lưu toàn bộ weight + BN ra .pth ────────────────────────────────────
cell1_model_dir = os.path.join(cfg.SAVE_DIR, "cell1_models")
os.makedirs(cell1_model_dir, exist_ok=True)
torch.save(enc_base.state_dict(),
           os.path.join(cell1_model_dir, "baseline_enc_full.pth"))
torch.save(dec_base.state_dict(),
           os.path.join(cell1_model_dir, "baseline_dec_full.pth"))
print(f"  [Save] Weights .pth → {cell1_model_dir}")

# Lưu weight ra hex (từng tham số)
def export_model_weights_hex(model, out_dir, prefix=""):
    os.makedirs(out_dir, exist_ok=True)
    for name, tensor in model.state_dict().items():
        if "num_batches_tracked" in name:
            continue
        safe = name.replace(".", "_")
        save_hex(float_to_q6_10(tensor.float()),
                 os.path.join(out_dir, f"{prefix}{safe}.hex"))
    print(f"  [HEX] Weight hex → {out_dir}")

export_model_weights_hex(enc_base, cell1_hex_dir, prefix="w_enc_base_")
export_model_weights_hex(dec_base, cell1_hex_dir, prefix="w_dec_base_")

# ── 1.7  Đo lường toàn dataset ──────────────────────────────────────────────
metrics_baseline = eval_dataset(enc_base, dec_base, dl_val,
                                 psnr_fn, ssim_fn, device,
                                 label="Baseline Float32")

print("\n[Cell 1] ✅ Hoàn tất Baseline.")

# %%===========================================================================
# CELL 2 – FINE-TUNE QAT (Q6.10)
# =============================================================================
"""
Yêu cầu:
  - Khởi tạo QATEncoder từ Baseline.
  - Fine-tune (ít epoch) giống stegano_fix_4_5.
  - Hiển thị 4 ảnh từ cặp mẫu Cell 1.
  - Xuất HEX input/output từ QAT model.
  - Đo PSNR/SSIM trên toàn dataset.
  - Lưu weight + BN của QAT model.
"""

# ── 2.0  Bootstrap (Cell 2 có thể chạy độc lập) ─────────────────────────────
cfg          = Config()
device       = cfg.DEVICE
torch.manual_seed(cfg.SEED)
os.makedirs(cfg.SAVE_DIR, exist_ok=True)
psnr_fn, ssim_fn = build_metrics(device)
dl_train, dl_val  = get_loaders(cfg)

# Load lại Baseline Encoder/Decoder để khởi tạo QAT từ đó
_enc_base_tmp = Encoder(base_c=cfg.BASE_CHANNEL).to(device)
_dec_base_tmp = Decoder(base_c=cfg.BASE_CHANNEL).to(device)
load_baseline_weights(_enc_base_tmp, _dec_base_tmp,
                      cfg.BASELINE_ENC_PTH, cfg.BASELINE_DEC_PTH, device)
_enc_base_tmp.eval(); _dec_base_tmp.eval()

# Lấy lại cặp ảnh mẫu
_batch        = next(iter(dl_val)).to(device)
SAMPLE_COVER  = _batch[:1].clone()
SAMPLE_SECRET = _batch[1:2].clone() if _batch.size(0) > 1 else _batch[:1].clone()
print(f"[Cell 2] Device={device} | Val batches={len(dl_val)}")

# ── 2.1  Khởi tạo QAT Encoder từ Baseline ────────────────────────────────────
enc_qat = QATEncoder(base_c=cfg.BASE_CHANNEL).to(device)

# Copy trọng số tương thích (tên key giống nhau, shape giống nhau)
def load_qat_from_baseline(qat_model, baseline_model):
    src = baseline_model.state_dict()
    dst = qat_model.state_dict()
    matched, skipped = {}, []
    for k, v in src.items():
        if k in dst and dst[k].shape == v.shape:
            matched[k] = v
        else:
            skipped.append(k)
    dst.update(matched)
    qat_model.load_state_dict(dst, strict=False)
    pct = 100.0 * len(matched) / max(len(dst), 1)
    print(f"  [QAT Init] Matched {len(matched)}/{len(dst)} keys ({pct:.1f}%)")
    if skipped:
        print(f"  [QAT Init] Skipped: {skipped[:5]}...")

load_qat_from_baseline(enc_qat, _enc_base_tmp)

# Kiểm tra nhanh: in các key còn thiếu sau khi load
_missing = [k for k in enc_qat.state_dict()
            if k not in _enc_base_tmp.state_dict()]
if _missing:
    print(f"  [INFO] Key có trong QAT nhưng không có trong Baseline "
          f"(BN/QuantIdentity mới thêm – bình thường): {_missing[:6]}"
          f"{'...' if len(_missing)>6 else ''}")
else:
    print("  [QAT Init] ✅ Tất cả key Baseline đã được copy sang QAT.")

# Decoder tiếp tục dùng Baseline (Float32) – copy state dict
dec_qat = Decoder(base_c=cfg.BASE_CHANNEL).to(device)
dec_qat.load_state_dict(_dec_base_tmp.state_dict(), strict=True)

# ── 2.2  Vòng lặp Fine-tune ─────────────────────────────────────────────────
optimizer = optim.Adam(
    list(enc_qat.parameters()) + list(dec_qat.parameters()),
    lr=cfg.QAT_LR, betas=(0.5, 0.999))
l1_loss = nn.L1Loss()
l2_loss = nn.MSELoss()

best_score_qat = float('inf')
qat_model_dir  = os.path.join(cfg.SAVE_DIR, "cell2_qat_models")
os.makedirs(qat_model_dir, exist_ok=True)

print(f"\n[Cell 2] Bắt đầu QAT Fine-tune ({cfg.QAT_EPOCHS} epochs)...")
for epoch in range(1, cfg.QAT_EPOCHS + 1):
    enc_qat.train(); dec_qat.train()
    t0 = time.time()
    running = {"Loss_G": 0., "Cov": 0., "Sec": 0.}

    for step, cover in enumerate(dl_train, start=1):
        cover  = cover.to(device)
        secret = cover[torch.randperm(cover.size(0), device=device)]

        optimizer.zero_grad(set_to_none=True)
        stego   = enc_qat(cover, secret)
        recover = dec_qat(stego)

        loss_cov = (cfg.LAMBDA_COVER_L1  * l1_loss(stego,   cover) +
                    cfg.LAMBDA_COVER_L2  * l2_loss(stego,   cover))
        loss_sec = (cfg.LAMBDA_SECRET_L1 * l1_loss(recover, secret) +
                    cfg.LAMBDA_SECRET_L2 * l2_loss(recover, secret))
        loss_g   = loss_cov + loss_sec
        loss_g.backward()
        torch.nn.utils.clip_grad_norm_(
            list(enc_qat.parameters()) + list(dec_qat.parameters()), 1.0)
        optimizer.step()

        running["Loss_G"] += loss_g.item()
        running["Cov"]    += loss_cov.item()
        running["Sec"]    += loss_sec.item()

        if step % 200 == 0:
            print(f"  [FT] E{epoch} Step{step}/{len(dl_train)} | "
                  f"Loss_G={loss_g.item():.5f} | "
                  f"Cov={loss_cov.item():.5f} | Sec={loss_sec.item():.5f}")

    n_steps = max(len(dl_train), 1)
    score = (running["Cov"] + running["Sec"]) / n_steps
    dt = time.time() - t0
    print(f"  [FT] Epoch {epoch}/{cfg.QAT_EPOCHS} | "
          f"Score={score:.5f} | Time={dt:.1f}s")

    # Save best
    if score < best_score_qat:
        best_score_qat = score
        torch.save(enc_qat.state_dict(),
                   os.path.join(qat_model_dir, "best_enc_qat.pth"))
        torch.save(dec_qat.state_dict(),
                   os.path.join(qat_model_dir, "best_dec_qat.pth"))

# Load best checkpoint
enc_qat.load_state_dict(torch.load(
    os.path.join(qat_model_dir, "best_enc_qat.pth"), map_location=device))
dec_qat.load_state_dict(torch.load(
    os.path.join(qat_model_dir, "best_dec_qat.pth"), map_location=device))
enc_qat.eval(); dec_qat.eval()

# ── 2.3  Chạy cặp mẫu Cell 1 qua QAT ────────────────────────────────────────
with torch.no_grad():
    SAMPLE_STEGO_QAT   = enc_qat(SAMPLE_COVER, SAMPLE_SECRET)
    SAMPLE_RECOVER_QAT = dec_qat(SAMPLE_STEGO_QAT)

show_4_images(
    SAMPLE_COVER, SAMPLE_SECRET,
    SAMPLE_STEGO_QAT, SAMPLE_RECOVER_QAT,
    title="Cell 2 – QAT Fine-tuned (Q6.10)",
    save_path=os.path.join(cfg.SAVE_DIR, "cell2_qat_sample.png"))

# ── 2.4  Xuất HEX input/output QAT ──────────────────────────────────────────
cell2_hex_dir = os.path.join(cfg.SAVE_DIR, "cell2_hex")
export_io_hex(SAMPLE_COVER, SAMPLE_SECRET,
              SAMPLE_STEGO_QAT, SAMPLE_RECOVER_QAT,
              cell2_hex_dir, prefix="qat_")

# ── 2.5  Đo lường toàn dataset ──────────────────────────────────────────────
metrics_qat = eval_dataset(enc_qat, dec_qat, dl_val,
                            psnr_fn, ssim_fn, device,
                            label="QAT Fine-tuned (Q6.10)")

# ── 2.6  Lưu weight + BN QAT model ──────────────────────────────────────────
export_model_weights_hex(enc_qat, cell2_hex_dir, prefix="w_enc_qat_")
export_model_weights_hex(dec_qat, cell2_hex_dir, prefix="w_dec_qat_")
print(f"  [Save] QAT .pth → {qat_model_dir}")
print("\n[Cell 2] ✅ Hoàn tất QAT Fine-tune.")

# %%===========================================================================
# CELL 3 – FUSE BATCHNORM
# =============================================================================
"""
Yêu cầu:
  - Gộp BatchNorm vào Pointwise Conv của QAT Encoder.
  - Hiển thị 4 ảnh cặp mẫu qua Fused Model.
  - Xuất HEX input/output Fused.
  - Đo MAE + torch.allclose(atol=1e-5) giữa Cell 2 và Cell 3.
"""

# ── 3.0  Bootstrap (Cell 3 có thể chạy độc lập) ─────────────────────────────
cfg           = Config()
device        = cfg.DEVICE
torch.manual_seed(cfg.SEED)
os.makedirs(cfg.SAVE_DIR, exist_ok=True)
psnr_fn, ssim_fn = build_metrics(device)
dl_train, dl_val  = get_loaders(cfg)

# Lấy lại cặp ảnh mẫu
_batch        = next(iter(dl_val)).to(device)
SAMPLE_COVER  = _batch[:1].clone()
SAMPLE_SECRET = _batch[1:2].clone() if _batch.size(0) > 1 else _batch[:1].clone()

# Load QAT checkpoint từ Cell 2
qat_model_dir = os.path.join(cfg.SAVE_DIR, "cell2_qat_models")
_enc_ckpt     = os.path.join(qat_model_dir, "best_enc_qat.pth")
_dec_ckpt     = os.path.join(qat_model_dir, "best_dec_qat.pth")

enc_qat = QATEncoder(base_c=cfg.BASE_CHANNEL).to(device)
dec_qat = Decoder(base_c=cfg.BASE_CHANNEL).to(device)

if os.path.exists(_enc_ckpt):
    enc_qat.load_state_dict(torch.load(_enc_ckpt, map_location=device))
    print(f"  [Load] enc_qat ← {_enc_ckpt}")
else:
    raise FileNotFoundError(
        f"Không tìm thấy checkpoint: {_enc_ckpt}\n"
        "Hãy chạy Cell 2 trước hoặc kiểm tra lại SAVE_DIR trong Config.")

if os.path.exists(_dec_ckpt):
    dec_qat.load_state_dict(torch.load(_dec_ckpt, map_location=device))
    print(f"  [Load] dec_qat ← {_dec_ckpt}")
else:
    raise FileNotFoundError(
        f"Không tìm thấy checkpoint: {_dec_ckpt}\n"
        "Hãy chạy Cell 2 trước hoặc kiểm tra lại SAVE_DIR trong Config.")

enc_qat.eval(); dec_qat.eval()
print(f"[Cell 3] Device={device} | enc_qat và dec_qat đã load xong.")

# ── 3.1  Hàm fuse_conv_bn ────────────────────────────────────────────────────
def fuse_conv_bn_into_conv(conv: nn.Conv2d, bn: nn.BatchNorm2d):
    """
    Gộp BN vào Conv (Pointwise):
        w_fused = w * (gamma / sqrt(var+eps))
        b_fused = beta + (b_conv - mean) * (gamma / sqrt(var+eps))
    Trả về Conv2d mới có bias, BN đã được "hấp thụ".
    """
    with torch.no_grad():
        gamma    = bn.weight
        beta     = bn.bias
        mean     = bn.running_mean
        var_sqrt = torch.sqrt(bn.running_var + bn.eps)
        scale    = (gamma / var_sqrt)

        b_conv = conv.bias if conv.bias is not None \
                 else torch.zeros_like(mean)

        w_fused = conv.weight * scale.view(-1, 1, 1, 1)
        b_fused = beta + (b_conv - mean) * scale

    # Tạo fused conv trên cùng device với conv gốc
    target_device = conv.weight.device
    fused_conv = nn.Conv2d(
        conv.in_channels, conv.out_channels,
        kernel_size=conv.kernel_size,
        stride=conv.stride, padding=conv.padding,
        groups=conv.groups, bias=True).to(target_device)
    fused_conv.weight.data.copy_(w_fused)
    fused_conv.bias.data.copy_(b_fused)
    return fused_conv

def fuse_model_qat(model: nn.Module) -> nn.Module:
    """
    Duyệt các nn.Sequential chứa (QATSeparableConv2d, BatchNorm2d, ...):
      - Fuse BN vào pointwise Conv của QATSeparableConv2d.
      - Set flag `bn_fused = True` để forward không quantize weight fused.
      - Thay BN bằng nn.Identity().
    """
    fused_count = 0
    for name, seq in model.named_modules():
        if not isinstance(seq, nn.Sequential) or len(seq) < 2:
            continue
        if isinstance(seq[0], QATSeparableConv2d) and \
           isinstance(seq[1], nn.BatchNorm2d):
            seq[0].pointwise = fuse_conv_bn_into_conv(seq[0].pointwise, seq[1])
            seq[0].bn_fused  = True      # ← báo forward dùng weight fused trực tiếp
            seq[1] = nn.Identity()
            fused_count += 1
    print(f"  [Fuse] Đã gộp {fused_count} khối (Conv+BN → FusedConv).")
    return model

# ── 3.2  Tạo Fused Model ─────────────────────────────────────────────────────
enc_fused = copy.deepcopy(enc_qat).eval()
enc_fused = fuse_model_qat(enc_fused)

# ── 3.3  Hiển thị 4 ảnh cặp mẫu qua Fused ───────────────────────────────────
with torch.no_grad():
    SAMPLE_STEGO_FUSED   = enc_fused(SAMPLE_COVER, SAMPLE_SECRET)
    SAMPLE_RECOVER_FUSED = dec_qat(SAMPLE_STEGO_FUSED)

show_4_images(
    SAMPLE_COVER, SAMPLE_SECRET,
    SAMPLE_STEGO_FUSED, SAMPLE_RECOVER_FUSED,
    title="Cell 3 – Fused BN Model",
    save_path=os.path.join(cfg.SAVE_DIR, "cell3_fused_sample.png"))

# ── 3.4  Xuất HEX input/output Fused ────────────────────────────────────────
cell3_hex_dir = os.path.join(cfg.SAVE_DIR, "cell3_hex")
export_io_hex(SAMPLE_COVER, SAMPLE_SECRET,
              SAMPLE_STEGO_FUSED, SAMPLE_RECOVER_FUSED,
              cell3_hex_dir, prefix="fused_")

# ── 3.5  Đo MAE + allclose giữa QAT (Cell 2) và Fused (Cell 3) ──────────────
print("\n[Cell 3] ── Kiểm tra tính tương đương QAT ↔ Fused ──")
print("  (Xử lý batch nhỏ để tránh OOM, tối đa 1000 ảnh)")

_test_ds     = dl_val.dataset
_n_test      = min(1000, len(_test_ds))
_VERIFY_BS   = 16          # batch nhỏ, an toàn cho mọi GPU
_rng         = torch.Generator(); _rng.manual_seed(99)

# Accumulators (CPU để tiết kiệm VRAM)
_mae_stego_acc   = 0.0
_mae_rec_acc     = 0.0
_max_diff_acc    = 0.0
_allclose_stego  = True
_allclose_rec    = True
_n_batches       = 0

enc_qat.eval(); enc_fused.eval(); dec_qat.eval()

with torch.no_grad():
    for _start in range(0, _n_test, _VERIFY_BS):
        _end    = min(_start + _VERIFY_BS, _n_test)
        _idx    = list(range(_start, _end))
        _cover  = torch.stack([_test_ds[i] for i in _idx]).to(device)
        _perm   = torch.randperm(len(_idx), generator=_rng)
        _secret = _cover[_perm]

        _sq  = enc_qat(   _cover, _secret).cpu()
        _sf  = enc_fused( _cover, _secret).cpu()
        _rq  = dec_qat(_sq.to(device)).cpu()
        _rf  = dec_qat(_sf.to(device)).cpu()

        _diff_s = torch.abs(_sq - _sf)
        _diff_r = torch.abs(_rq - _rf)

        _mae_stego_acc  += _diff_s.mean().item()
        _mae_rec_acc    += _diff_r.mean().item()
        _max_diff_acc    = max(_max_diff_acc, _diff_s.max().item())
        _allclose_stego  = _allclose_stego and bool(
            torch.allclose(_sq, _sf, atol=1e-5))
        _allclose_rec    = _allclose_rec and bool(
            torch.allclose(_rq, _rf, atol=1e-5))
        _n_batches += 1

        # Giải phóng VRAM ngay
        del _cover, _secret, _sq, _sf, _rq, _rf, _diff_s, _diff_r
        torch.cuda.empty_cache()

mae_stego   = _mae_stego_acc  / max(_n_batches, 1)
mae_recover = _mae_rec_acc    / max(_n_batches, 1)
max_diff_stego  = _max_diff_acc
allclose_stego  = _allclose_stego
allclose_recover = _allclose_rec

print(f"  Stego  : MAE={mae_stego:.2e} | allclose(atol=1e-5)={allclose_stego}"
      f" | max_diff={max_diff_stego:.2e}")
print(f"  Recover: MAE={mae_recover:.2e} | allclose(atol=1e-5)={allclose_recover}")
if allclose_stego and allclose_recover:
    print("  ✅ Fuse BN KHÔNG làm sai lệch thuật toán.")
else:
    print("  ⚠ Fuse BN có sai số nhỏ (thường do FP32 round-off) – kiểm tra lại.")

# ── 3.6  Lưu weight Fused Model (BN đã hấp thụ) ─────────────────────────────
cell3_model_dir = os.path.join(cfg.SAVE_DIR, "cell3_models")
os.makedirs(cell3_model_dir, exist_ok=True)

# Lưu state_dict dạng .pth
fused_enc_pth = os.path.join(cell3_model_dir, "fused_enc.pth")
torch.save(enc_fused.state_dict(), fused_enc_pth)
print(f"  [Save] Fused Encoder state_dict → {fused_enc_pth}")

# Lưu toàn bộ model (kèm kiến trúc) dạng .pth để dễ load lại
fused_enc_full_pth = os.path.join(cell3_model_dir, "fused_enc_full.pth")
torch.save(enc_fused, fused_enc_full_pth)
print(f"  [Save] Fused Encoder full model  → {fused_enc_full_pth}")

# Lưu weight ra hex (từng tham số, Q6.10) – loại bỏ các key BN dư thừa
cell3_hex_weight_dir = os.path.join(cell3_model_dir, "hex_weights")
export_model_weights_hex(enc_fused, cell3_hex_weight_dir, prefix="w_enc_fused_")

# In tóm tắt các tham số đã lưu (tên + shape)
print(f"\n  {'Tham số':<55} {'Shape'}")
print("  " + "-"*75)
for k, v in enc_fused.state_dict().items():
    if "num_batches_tracked" in k:
        continue
    print(f"  {k:<55} {str(list(v.shape))}")

print(f"\n  Thư mục lưu weights: {cell3_model_dir}")
print("\n[Cell 3] ✅ Hoàn tất Fuse BN.")

# %%===========================================================================
# CELL 4 – XUẤT MEMORY FILE (.mem) CHO FPGA
# =============================================================================
"""
Yêu cầu:
  - Từ Fused Model (Cell 3), xuất depthwise.mem và pointwise.mem.
  - In bảng memory map (tên lớp, địa chỉ bắt đầu, số từ).
"""

def float_to_hex_lines(tensor: torch.Tensor, scale: float = Q_SCALE):
    """Tensor float → list các chuỗi hex 16-bit (two's complement)."""
    arr = tensor.detach().cpu().numpy().flatten()
    arr_i = np.clip(np.round(arr * scale), INT16_MIN, INT16_MAX).astype(np.int32)
    return [f"{v & 0xFFFF:04x}" for v in arr_i]

def export_mem_files(model: nn.Module, output_dir: str,
                     insert_deadbeef_after_head: bool = True):
    """
    Duyệt Fused Encoder, ghi:
      depthwise.mem – trọng số tất cả Depthwise Conv
      pointwise.mem – trọng số tất cả Pointwise Conv (kèm bias nếu có)

    Tham số insert_deadbeef_after_head:
      Chèn 0xDEAD 0xBEEF (alignment marker) sau head depthwise.
    """
    os.makedirs(output_dir, exist_ok=True)
    dw_path = os.path.join(output_dir, "depthwise.mem")
    pw_path = os.path.join(output_dir, "pointwise.mem")

    addr_dw, addr_pw = 0, 0
    map_info = []
    is_head = True  # cờ để chèn alignment marker

    with open(dw_path, "w") as f_dw, open(pw_path, "w") as f_pw:
        for name, module in model.named_modules():

            # ── Depthwise Conv (groups > 1) ────────────────────────────────
            if isinstance(module, nn.Conv2d) and module.groups > 1:
                lines = float_to_hex_lines(module.weight)
                cnt   = len(lines)
                f_dw.write("\n".join(lines) + "\n")
                map_info.append({
                    "file": "DW", "layer": name,
                    "addr_start": addr_dw, "words": cnt,
                    "shape": str(list(module.weight.shape))})
                addr_dw += cnt

                # if insert_deadbeef_after_head and is_head:
                #     f_dw.write("dead\nbeef\n")
                #     map_info.append({
                #         "file": "DW", "layer": "[ALIGN_DEADBEEF]",
                #         "addr_start": addr_dw, "words": 2, "shape": "–"})
                #     addr_dw += 2
                #     is_head = False

            # ── Pointwise Conv (kernel_size == 1 × 1) ─────────────────────
            elif isinstance(module, nn.Conv2d) and \
                 module.kernel_size == (1, 1) and module.groups == 1:
                # Weight
                w_lines = float_to_hex_lines(module.weight)
                cnt_w   = len(w_lines)
                f_pw.write("\n".join(w_lines) + "\n")
                map_info.append({
                    "file": "PW", "layer": name + ".weight",
                    "addr_start": addr_pw, "words": cnt_w,
                    "shape": str(list(module.weight.shape))})
                addr_pw += cnt_w

                # Bias (nếu có – sau fuse BN luôn có)
                if module.bias is not None:
                    b_lines = float_to_hex_lines(module.bias)
                    cnt_b   = len(b_lines)
                    f_pw.write("\n".join(b_lines) + "\n")
                    map_info.append({
                        "file": "PW", "layer": name + ".bias",
                        "addr_start": addr_pw, "words": cnt_b,
                        "shape": str(list(module.bias.shape))})
                    addr_pw += cnt_b

    # In bảng memory map
    print(f"\n[Cell 4] ── Memory Map ({len(map_info)} entries) ──")
    print(f"  {'File':<4} {'Layer':<45} {'Addr_Start':>10} {'Words':>8} {'Shape'}")
    print("  " + "-"*85)
    for row in map_info:
        print(f"  {row['file']:<4} {row['layer']:<45} "
              f"{row['addr_start']:>10} {row['words']:>8}  {row['shape']}")
    print(f"\n  DW total words : {addr_dw}")
    print(f"  PW total words : {addr_pw}")
    print(f"\n  depthwise.mem  → {dw_path}")
    print(f"  pointwise.mem  → {pw_path}")

    # Lưu map ra CSV
    map_csv = os.path.join(output_dir, "memory_map.csv")
    with open(map_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(map_info[0].keys()))
        writer.writeheader(); writer.writerows(map_info)
    print(f"  memory_map.csv → {map_csv}")

    return dw_path, pw_path, map_info

# ── 4.0  Bootstrap (Cell 4 có thể chạy độc lập) ─────────────────────────────
cfg    = Config()
device = cfg.DEVICE
os.makedirs(cfg.SAVE_DIR, exist_ok=True)

# Load Fused Encoder từ checkpoint Cell 3
cell3_model_dir  = os.path.join(cfg.SAVE_DIR, "cell3_models")
_fused_enc_ckpt  = os.path.join(cell3_model_dir, "fused_enc.pth")

enc_fused = QATEncoder(base_c=cfg.BASE_CHANNEL).to(device)
# Fuse BN trước khi load (kiến trúc phải khớp với state_dict đã fuse)
enc_fused = fuse_model_qat(enc_fused)

if os.path.exists(_fused_enc_ckpt):
    enc_fused.load_state_dict(torch.load(_fused_enc_ckpt, map_location=device))
    print(f"  [Load] enc_fused ← {_fused_enc_ckpt}")
else:
    raise FileNotFoundError(
        f"Không tìm thấy checkpoint: {_fused_enc_ckpt}\n"
        "Hãy chạy Cell 3 trước hoặc kiểm tra lại SAVE_DIR trong Config.")

enc_fused.eval()
print(f"[Cell 4] Device={device} | enc_fused đã load xong.")

# Thực thi
cell4_mem_dir = os.path.join(cfg.SAVE_DIR, "cell4_fpga_mem")
enc_fused_cpu = copy.deepcopy(enc_fused).cpu().eval()
dw_path, pw_path, mem_map = export_mem_files(
    enc_fused_cpu, cell4_mem_dir,
    insert_deadbeef_after_head=True)

print("\n[Cell 4] ✅ Hoàn tất xuất file .mem cho FPGA.")

# %%===========================================================================
# CELL 4.5 – SẮP XẾP LẠI DEPTHWISE (9 Banks) & POINTWISE (16 Banks)
# =============================================================================
"""
Yêu cầu:
  A. Depthwise 9 Banks:
     - Đọc depthwise.mem từ Cell 4, lọc bỏ dead/beef markers.
     - Sắp xếp lại theo 9 Banks (mỗi bank = 1 vị trí không gian kernel 3×3).
     - Mỗi hàng 64-bit = 4 channels (Little Endian: IC3_IC2_IC1_IC0).
     - Pad số channel lên bội số 16 (hardware alignment).
     - Xuất ra depthwise_9banks.mem.

  B. Pointwise 16 Banks:
     - Đọc pointwise.mem từ Cell 4.
     - Phân tách Weight [OC][IC] và Bias theo topology mô hình.
     - Phân bổ theo 16 Banks (OC % 16 == bank_id).
     - Weight: pad IC lên bội số 16, gom 4 IC / hàng 64-bit LE.
     - Bias  : định dạng 000000000000<bias_hex> (64-bit, 3 words dump + 1 bias).
     - Xuất ra pointwise_16banks.mem.
"""

import math as _math

# ══════════════════════════════════════════════════════════════════════════════
# PHẦN A – DEPTHWISE 9 BANKS
# ══════════════════════════════════════════════════════════════════════════════

def _build_dw_layer_map(model: nn.Module):
    """Tự động lấy (tên_rút_gọn, in_channels) của từng DW Conv theo thứ tự."""
    lmap = []
    for name, m in model.named_modules():
        if isinstance(m, nn.Conv2d) and m.groups > 1 and \
           m.kernel_size == (3, 3):
            # Rút tên ngắn: "head.0.depthwise" → "head"
            short = name.split(".")[0]
            lmap.append((short, m.in_channels))
    return lmap

def rearrange_depthwise_9banks(input_filepath: str, output_filepath: str,
                                layer_map: list):
    """
    Đọc depthwise.mem (flat 16-bit hex, 1 word/dòng),
    sắp xếp theo 9 Banks kernel 3×3, pad channel lên bội 16,
    ghi ra 64-bit Little Endian (4 channels / hàng).
    """
    print(f"\n[Cell 4.5-A] Đọc depthwise.mem: {input_filepath}")

    with open(input_filepath, "r") as f:
        lines = f.read().splitlines()

    # Lọc marker, comment, dòng trống
    raw_data = []
    for line in lines:
        s = line.strip().lower()
        if not s or s.startswith("//") or s in ("dead", "beef"):
            continue
        raw_data.append(s)
    print(f"  Words 16-bit (sau lọc): {len(raw_data)}")

    # Phân tách theo layer; PyTorch shape [C,1,3,3] → flatten: ch0_sp0..sp8, ch1_sp0..
    parsed_layers = []
    ptr = 0
    for name, c in layer_map:
        num_w = c * 9
        chunk = raw_data[ptr: ptr + num_w]
        ptr  += num_w
        if len(chunk) != num_w:
            print(f"  ⚠ LỖI layer '{name}': cần {num_w}, còn {len(chunk)}. Dừng.")
            return None
        # Nhóm theo 9 vị trí không gian: spatial[sp] = [ch0, ch1, ..., chC-1]
        spatial = [[] for _ in range(9)]
        for ch in range(c):
            for sp in range(9):
                spatial[sp].append(chunk[ch * 9 + sp])
        parsed_layers.append({"name": name, "c": c, "spatial": spatial})

    if ptr != len(raw_data):
        print(f"  ⚠ Còn {len(raw_data) - ptr} words chưa đọc (layer_map thiếu?).")

    # Ghi 9 Banks
    os.makedirs(os.path.dirname(os.path.abspath(output_filepath)), exist_ok=True)
    total_rows = 0
    with open(output_filepath, "w") as f_out:
        for sp in range(9):
            ky, kx = sp // 3, sp % 3
            f_out.write(f"// =========================================\n")
            f_out.write(f"// BANK POSITION ({ky}, {kx})\n")
            f_out.write(f"// =========================================\n")
            for layer in parsed_layers:
                c        = layer["c"]
                w_list   = layer["spatial"][sp]
                padded_c = _math.ceil(c / 16) * 16
                w_padded = w_list + ["0000"] * (padded_c - c)
                f_out.write(f"// Layer: {layer['name']} (C={c}, padded={padded_c})\n")
                for i in range(0, padded_c, 4):
                    ic0, ic1, ic2, ic3 = (w_padded[i],   w_padded[i+1],
                                          w_padded[i+2], w_padded[i+3])
                    f_out.write(f"{ic3}{ic2}{ic1}{ic0}\n")
                    total_rows += 1

    # Tóm tắt
    print(f"\n  {'Layer':<16} {'C':>5} {'Padded':>8} {'Rows/bank':>10}")
    print("  " + "-"*42)
    for layer in parsed_layers:
        pc = _math.ceil(layer['c'] / 16) * 16
        print(f"  {layer['name']:<16} {layer['c']:>5} {pc:>8} {pc//4:>10}")
    print(f"\n  Tổng hàng 64-bit : {total_rows}")
    print(f"  Xuất             : {output_filepath}")
    return output_filepath

# ══════════════════════════════════════════════════════════════════════════════
# PHẦN B – POINTWISE 16 BANKS
# ══════════════════════════════════════════════════════════════════════════════

def _build_pw_topology(model: nn.Module):
    """
    Tự động xây topology Pointwise từ Fused Encoder.
    Mỗi entry: {"name", "ic", "oc", "has_bias"}
    Chỉ lấy Conv2d kernel_size=1×1, groups=1 (pointwise).
    """
    topology = []
    for name, m in model.named_modules():
        if isinstance(m, nn.Conv2d) and m.kernel_size == (1, 1) \
                and m.groups == 1:
            short = name.split(".")[0]
            topology.append({
                "name":     short,
                "ic":       m.in_channels,
                "oc":       m.out_channels,
                "has_bias": m.bias is not None,
            })
    return topology

def rearrange_pointwise_16banks(input_filepath: str, output_filepath: str,
                                 topology: list):
    """
    Đọc pointwise.mem (flat 16-bit hex),
    phân tách Weight[OC][IC] + Bias theo topology,
    phân bổ vào 16 Banks (OC % 16 == bank_id),
    ghi ra 64-bit LE; bias dạng 000000000000<BIAS>.
    """
    print(f"\n[Cell 4.5-B] Đọc pointwise.mem: {input_filepath}")

    with open(input_filepath, "r") as f:
        lines = f.read().splitlines()

    raw_data = [l.strip().lower() for l in lines
                if l.strip() and not l.strip().startswith("//")]
    print(f"  Words 16-bit (raw): {len(raw_data)}")

    # Phân tách từng layer
    parsed_layers = []
    ptr = 0
    for layer in topology:
        ic, oc = layer["ic"], layer["oc"]
        w_size = oc * ic
        weights_flat = raw_data[ptr: ptr + w_size];  ptr += w_size

        biases = []
        if layer["has_bias"]:
            biases = raw_data[ptr: ptr + oc];  ptr += oc

        # Tổ chức thành [OC][IC]
        weights_2d = []
        for o in range(oc):
            weights_2d.append(weights_flat[o * ic: (o + 1) * ic])

        parsed_layers.append({
            "name":     layer["name"],
            "ic":       ic,
            "oc":       oc,
            "has_bias": layer["has_bias"],
            "weights":  weights_2d,
            "biases":   biases,
        })

    if ptr != len(raw_data):
        print(f"  ⚠ Còn {len(raw_data) - ptr} words chưa đọc.")

    # Ghi 16 Banks
    os.makedirs(os.path.dirname(os.path.abspath(output_filepath)), exist_ok=True)
    total_w_rows = 0
    total_b_rows = 0

    print(f"  Phân bổ vào 16 Banks → {output_filepath}")
    with open(output_filepath, "w") as f_out:
        for bank in range(16):
            f_out.write(f"// ==================================================\n")
            f_out.write(f"// BANK {bank}\n")
            f_out.write(f"// ==================================================\n\n")

            # ── Weights ───────────────────────────────────────────────────────
            f_out.write(f"// --- WEIGHTS ---\n")
            for layer in parsed_layers:
                valid_ocs = [oc for oc in range(layer["oc"])
                             if oc % 16 == bank]
                if not valid_ocs:
                    continue
                f_out.write(f"// Layer: {layer['name']} | IC: {layer['ic']}\n")
                for oc in valid_ocs:
                    f_out.write(f"//   OC: {oc}\n")
                    ic_list  = layer["weights"][oc]
                    c        = layer["ic"]
                    padded_c = _math.ceil(c / 16) * 16
                    padded_ic = ic_list + ["0000"] * (padded_c - c)
                    for i in range(0, padded_c, 4):
                        ic0, ic1, ic2, ic3 = (padded_ic[i],   padded_ic[i+1],
                                              padded_ic[i+2], padded_ic[i+3])
                        f_out.write(f"{ic3}{ic2}{ic1}{ic0}\n")
                        total_w_rows += 1

            f_out.write("\n")

            # ── Biases ────────────────────────────────────────────────────────
            f_out.write(f"// --- BIASES ---\n")
            for layer in parsed_layers:
                if not layer["has_bias"]:
                    continue
                valid_ocs = [oc for oc in range(layer["oc"])
                             if oc % 16 == bank]
                if not valid_ocs:
                    continue
                f_out.write(f"// Layer: {layer['name']}\n")
                for oc in valid_ocs:
                    bval = layer["biases"][oc]
                    # 64-bit: [63:16]=0x000000000000, [15:0]=bias
                    f_out.write(f"000000000000{bval} // OC {oc}\n")
                    total_b_rows += 1

            f_out.write("\n\n")

    print(f"\n  {'Layer':<16} {'IC':>5} {'OC':>5} {'Bias':>6}")
    print("  " + "-"*34)
    for layer in parsed_layers:
        print(f"  {layer['name']:<16} {layer['ic']:>5} {layer['oc']:>5}"
              f"  {'Yes' if layer['has_bias'] else 'No':>5}")
    print(f"\n  Hàng weight 64-bit : {total_w_rows}")
    print(f"  Hàng bias  64-bit  : {total_b_rows}")
    print(f"  Xuất               : {output_filepath}")
    return output_filepath

# ══════════════════════════════════════════════════════════════════════════════
# 4.5-0  Bootstrap (Cell 4.5 có thể chạy độc lập)
# ══════════════════════════════════════════════════════════════════════════════
cfg    = Config()
device = cfg.DEVICE
os.makedirs(cfg.SAVE_DIR, exist_ok=True)

# Load enc_fused_cpu từ checkpoint Cell 3 (cần để xây dw_layer_map / pw_topology)
cell3_model_dir = os.path.join(cfg.SAVE_DIR, "cell3_models")
_fused_enc_ckpt = os.path.join(cell3_model_dir, "fused_enc.pth")
enc_fused = QATEncoder(base_c=cfg.BASE_CHANNEL)
enc_fused = fuse_model_qat(enc_fused)
if os.path.exists(_fused_enc_ckpt):
    enc_fused.load_state_dict(torch.load(_fused_enc_ckpt, map_location="cpu"))
    print(f"  [Load] enc_fused ← {_fused_enc_ckpt}")
else:
    raise FileNotFoundError(
        f"Không tìm thấy checkpoint: {_fused_enc_ckpt}\n"
        "Hãy chạy Cell 3 trước hoặc kiểm tra lại SAVE_DIR trong Config.")
enc_fused_cpu = enc_fused.cpu().eval()

# Đường dẫn .mem từ Cell 4
cell4_mem_dir = os.path.join(cfg.SAVE_DIR, "cell4_fpga_mem")
dw_path = os.path.join(cell4_mem_dir, "depthwise.mem")
pw_path = os.path.join(cell4_mem_dir, "pointwise.mem")
for _p in (dw_path, pw_path):
    if not os.path.exists(_p):
        raise FileNotFoundError(
            f"Không tìm thấy file: {_p}\n"
            "Hãy chạy Cell 4 trước.")
print(f"[Cell 4.5] Device={device} | .mem files OK.")

# ══════════════════════════════════════════════════════════════════════════════
# THỰC THI
# ══════════════════════════════════════════════════════════════════════════════
cell45_out_dir = os.path.join(cfg.SAVE_DIR, "cell45_arranged")
dw_9banks_path = os.path.join(cell45_out_dir, "depthwise_9banks.mem")
pw_16banks_path = os.path.join(cell45_out_dir, "pointwise_16banks.mem")

# Tự động lấy layer map từ Fused Encoder (đúng dù base_c thay đổi)
_dw_layer_map = _build_dw_layer_map(enc_fused_cpu)
_pw_topology  = _build_pw_topology(enc_fused_cpu)

print(f"[Cell 4.5] DW layer map ({len(_dw_layer_map)} lớp):")
for _n, _c in _dw_layer_map:
    print(f"  {_n:<50} in_c={_c}")

print(f"\n[Cell 4.5] PW topology ({len(_pw_topology)} lớp):")
for _t in _pw_topology:
    print(f"  {_t['name']:<14} IC={_t['ic']:>4}  OC={_t['oc']:>4}"
          f"  bias={'Y' if _t['has_bias'] else 'N'}")

# A. Depthwise 9 Banks
rearrange_depthwise_9banks(
    input_filepath  = dw_path,          # depthwise.mem từ Cell 4
    output_filepath = dw_9banks_path,
    layer_map       = _dw_layer_map,
)

# B. Pointwise 16 Banks
rearrange_pointwise_16banks(
    input_filepath  = pw_path,          # pointwise.mem từ Cell 4
    output_filepath = pw_16banks_path,
    topology        = _pw_topology,
)

print(f"\n[Cell 4.5] ✅ Hoàn tất sắp xếp lại bộ nhớ FPGA.")
print(f"  depthwise_9banks.mem  → {dw_9banks_path}")
print(f"  pointwise_16banks.mem → {pw_16banks_path}")

# %%===========================================================================
# CELL 5 – XUẤT GOLDEN MODEL (Activations)
# =============================================================================
"""
Yêu cầu:
  - Dùng Hook PyTorch để trích xuất activations sau mỗi lớp.
  - Truyền 1 cặp ảnh mẫu (từ Cell 1) qua Fused Model.
  - Lưu mỗi feature map thành file .hex riêng.
  - In bảng tóm tắt (tên lớp, shape, range, overflow).
"""

# ── 5.1  Đăng ký hooks ───────────────────────────────────────────────────────
def register_activation_hooks(model: nn.Module, storage: dict,
                               target_types=None):
    """
    Gắn forward hook vào các layer thuộc target_types.
    Mặc định: Conv2d, ReLU, LeakyReLU, Tanh, QATSeparableConv2d, BatchNorm2d.
    Trả về list hooks (để remove sau khi dùng).
    """
    if target_types is None:
        target_types = (
            nn.Conv2d, nn.ReLU, nn.LeakyReLU, nn.Tanh,
            QATSeparableConv2d, nn.BatchNorm2d, nn.Identity)

    handles = []

    def make_hook(layer_name):
        def hook(module, inp, output):
            # Chỉ lưu tensor (bỏ qua Identity output rỗng)
            if isinstance(output, torch.Tensor):
                storage[layer_name] = output.detach().cpu().float()
        return hook

    for name, module in model.named_modules():
        if isinstance(module, target_types):
            safe = name.replace(".", "_") if name else module.__class__.__name__
            handles.append(module.register_forward_hook(make_hook(safe)))

    return handles

# ── 5.0  Bootstrap (Cell 5 có thể chạy độc lập) ─────────────────────────────
cfg    = Config()
device = cfg.DEVICE
os.makedirs(cfg.SAVE_DIR, exist_ok=True)

# Load Fused Encoder từ checkpoint Cell 3
cell3_model_dir = os.path.join(cfg.SAVE_DIR, "cell3_models")
_fused_enc_ckpt = os.path.join(cell3_model_dir, "fused_enc.pth")
enc_fused = QATEncoder(base_c=cfg.BASE_CHANNEL).to(device)
enc_fused = fuse_model_qat(enc_fused)
if os.path.exists(_fused_enc_ckpt):
    enc_fused.load_state_dict(torch.load(_fused_enc_ckpt, map_location=device))
    print(f"  [Load] enc_fused ← {_fused_enc_ckpt}")
else:
    raise FileNotFoundError(
        f"Không tìm thấy checkpoint: {_fused_enc_ckpt}\n"
        "Hãy chạy Cell 3 trước hoặc kiểm tra lại SAVE_DIR trong Config.")
enc_fused.eval()

# Load QAT Decoder từ checkpoint Cell 2 (dùng để recover ảnh kiểm chứng)
qat_model_dir = os.path.join(cfg.SAVE_DIR, "cell2_qat_models")
_dec_ckpt     = os.path.join(qat_model_dir, "best_dec_qat.pth")
dec_qat = Decoder(base_c=cfg.BASE_CHANNEL).to(device)
if os.path.exists(_dec_ckpt):
    dec_qat.load_state_dict(torch.load(_dec_ckpt, map_location=device))
    print(f"  [Load] dec_qat ← {_dec_ckpt}")
else:
    raise FileNotFoundError(
        f"Không tìm thấy checkpoint: {_dec_ckpt}\n"
        "Hãy chạy Cell 2 trước hoặc kiểm tra lại SAVE_DIR trong Config.")
dec_qat.eval()

# Lấy lại cặp ảnh mẫu từ val loader
dl_train, dl_val = get_loaders(cfg)
_batch        = next(iter(dl_val)).to(device)
SAMPLE_COVER  = _batch[:1].clone()
SAMPLE_SECRET = _batch[1:2].clone() if _batch.size(0) > 1 else _batch[:1].clone()
print(f"[Cell 5] Device={device} | Models & data đã sẵn sàng.")

# ── 5.2  Chuẩn bị ảnh đầu vào (giả lập FPGA: Q6.10 round-trip) ─────────────
cell5_dir = os.path.join(cfg.SAVE_DIR, "cell5_golden")
act_dir   = os.path.join(cell5_dir, "activations")
os.makedirs(act_dir, exist_ok=True)

# Lưu Input HEX
save_hex(float_to_q6_10(SAMPLE_COVER.cpu()),
         os.path.join(cell5_dir, "000_input_cover.hex"))
save_hex(float_to_q6_10(SAMPLE_SECRET.cpu()),
         os.path.join(cell5_dir, "000_input_secret.hex"))

# Lượng tử hóa input (mô phỏng FPGA nhận pixel 16-bit)
x_cov_sim = float_to_q6_10(SAMPLE_COVER.cpu()).float() / Q_SCALE
x_sec_sim = float_to_q6_10(SAMPLE_SECRET.cpu()).float() / Q_SCALE

# ── 5.3  Forward pass với hooks ──────────────────────────────────────────────
layer_outputs: dict = {}
enc_fused_cpu_golden = copy.deepcopy(enc_fused).cpu().eval()
hooks = register_activation_hooks(enc_fused_cpu_golden, layer_outputs)

with torch.no_grad():
    stego_golden = enc_fused_cpu_golden(x_cov_sim, x_sec_sim)

# Gỡ hooks ngay sau khi xong
for h in hooks:
    h.remove()

# ── 5.4  Lưu stego output ────────────────────────────────────────────────────
save_hex(float_to_q6_10(stego_golden),
         os.path.join(cell5_dir, "999_stego_output.hex"))

# ── 5.5  Lưu từng activation + in bảng tóm tắt ──────────────────────────────
print(f"\n[Cell 5] ── Golden Activations ({len(layer_outputs)} layers) ──")
print(f"  {'Layer':<40} {'Shape':<22} {'Min':>8} {'Max':>8} {'Overflow'}")
print("  " + "-"*90)

activation_summary = []
for idx, (name, feat) in enumerate(layer_outputs.items()):
    f_min = float(feat.min()); f_max = float(feat.max())
    overflow = (f_min < -32.0) or (f_max >= 32.0)
    flag = " ⚠ OVERFLOW" if overflow else "  OK"
    print(f"  {name:<40} {str(list(feat.shape)):<22} "
          f"{f_min:>8.4f} {f_max:>8.4f}  {flag}")

    # Lưu .hex
    hex_path = os.path.join(act_dir, f"{idx:03d}_{name}_out.hex")
    save_hex(float_to_q6_10(feat), hex_path)
    activation_summary.append({
        "index": idx, "layer": name,
        "shape": str(list(feat.shape)),
        "min": f_min, "max": f_max,
        "overflow_q6_10": overflow,
        "hex_file": hex_path})

# Lưu CSV tóm tắt
act_csv = os.path.join(cell5_dir, "activation_summary.csv")
with open(act_csv, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=list(activation_summary[0].keys()))
    writer.writeheader(); writer.writerows(activation_summary)

print(f"\n  Đã lưu {len(activation_summary)} file .hex vào: {act_dir}")
print(f"  Tóm tắt → {act_csv}")

# ── 5.6  Recover từ stego_golden rồi lưu ảnh kiểm chứng ─────────────────────
with torch.no_grad():
    recover_golden = dec_qat.cpu().eval()(stego_golden)

vutils.save_image(((SAMPLE_COVER.cpu() + 1) / 2).clamp(0, 1),
                  os.path.join(cell5_dir, "vis_cover.png"))
vutils.save_image(((SAMPLE_SECRET.cpu() + 1) / 2).clamp(0, 1),
                  os.path.join(cell5_dir, "vis_secret.png"))
vutils.save_image(((stego_golden + 1) / 2).clamp(0, 1),
                  os.path.join(cell5_dir, "vis_stego.png"))
vutils.save_image(((recover_golden + 1) / 2).clamp(0, 1),
                  os.path.join(cell5_dir, "vis_recover.png"))

print(f"\n  Ảnh kiểm chứng → {cell5_dir}")
print("\n[Cell 5] ✅ Hoàn tất Golden Model – sẵn sàng làm Testbench Verilog.")

# %%===========================================================================
# TỔNG KẾT
# =============================================================================
print("\n" + "="*70)
print("  PIPELINE HOÀN TẤT")
print("="*70)
print(f"  Thư mục kết quả : {cfg.SAVE_DIR}")
print(f"\n  Cell 1 – Baseline  : PSNR_C={metrics_baseline['PSNR_C']:.2f}dB | "
      f"SSIM_C={metrics_baseline['SSIM_C']:.4f} | "
      f"PSNR_S={metrics_baseline['PSNR_S']:.2f}dB | "
      f"SSIM_S={metrics_baseline['SSIM_S']:.4f}")
print(f"  Cell 2 – QAT       : PSNR_C={metrics_qat['PSNR_C']:.2f}dB | "
      f"SSIM_C={metrics_qat['SSIM_C']:.4f} | "
      f"PSNR_S={metrics_qat['PSNR_S']:.2f}dB | "
      f"SSIM_S={metrics_qat['SSIM_S']:.4f}")
print(f"  Cell 3 – Fuse BN   : allclose(stego)={allclose_stego} | "
      f"MAE={mae_stego:.2e}")
print(f"  Cell 4 – FPGA .mem : {dw_path}")
print(f"  Cell 5 – Golden    : {len(activation_summary)} activation .hex files")
print("="*70)